/* irdef.h - ir defines

   generated by genir 0.1.0-alpha 27 Jun 2022  2:20

   from irtyp.h 26 Jun 2022 22:05 */

#define insgrpbit 30 // 4
#define insgrpmsk 3

#define typbit 26 // 13
#define typmsk 0xf

#define regdbit 22 // 16
#define regdmsk 0xf

#define ldinsbit 20 // 4
#define ldinsmsk 3

#define ldmodbit 18 // 4
#define ldmodmsk 3

#define Ldimmbit 0 // 524288
#define Ldimmmsk 0x7ffff

#define Ldoirbit 0 // 131072
#define Ldoirmsk 0x1ffff

#define Ldshlbit 13 // 32
#define Ldshlmsk 0x1f

#define Ldtyp2bit 9 // 13
#define Ldtyp2msk 0xf

#define Ldoir2bit 0 // 256
#define Ldoir2msk 0xff

#define aopbit 14 // 14
#define aopmsk 0xf

#define amodbit 8 // 4
#define amodmsk 3

#define aoirbit 0 // 128
#define aoirmsk 0x7f

#define opsizbit 0 // 3
#define opsizmsk 3

#define ctinsbit 16 // 4
#define ctinsmsk 3

#define ccbit 13 // 7
#define ccmsk 7

#define ccofsbit 0 // 4096
#define ccofsmsk 0xfff

#define regs1bit 18 // 16
#define regs1msk 0xf

#define regs2bit 10 // 16
#define regs2msk 0xf

#define ctmodbit 28 // 4
#define ctmodmsk 3

#define ctoirbit 0 // 134217728
#define ctoirmsk 0x7ffffff


/*

ld 31-30 insgrp  29-26 typ  25-22 regd  21-20 ldins  19- 0 Ldimm
 19-18 ldmod  17- 0 Ldoir
  17-13 Ldshl   8- 0 Ldoir2
  17- 9 Ldtyp2  

ar 31-30 insgrp  29-26 typ  25-22 regd  21-18 regs1  13-10 regs2  17-14 aop   9- 8 amod   7- 0 aoir
 

ct 31-30 insgrp  29-26 typ  25-22 regd  21-18 regs1  17-16 ctins  15-13 cc  12- 0 ccofs
 29-28 ctmod  27- 0 ctoir
 

*/
