/* lex.c - lexical analysis pass

   This file is part of Morelia, a subset of Python with emphasis on efficiency.

   Copyright © 2022 Joris van der Geer.

   Morelia is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Morelia is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program, typically in the file License.txt
   If not, see http://www.gnu.org/licenses.
 */

#include <stdarg.h>
#include <string.h>
#include <stdlib.h>

#include "base.h"
#include "chr.h"

#include "os.h"

#include "mem.h"

#include "fmt.h"

static ub4 msgfile = Shsrc_lex;
#include "msg.h"

#include "dia.h"

#include "lexsyn.h"

// max brackets nesting and indents
#define Depth 256

// max token stream len
#define Tokencnt (1U << 24)

#define Emitdetail

// #define Addtrace

#if defined __clang__
 #pragma clang diagnostic ignored "-Wsign-conversion"
 #pragma clang diagnostic ignored "-Wduplicate-enum"
 #pragma clang diagnostic ignored "-Wgnu-label-as-value"
#elif defined __GNUC__
 #pragma GCC diagnostic ignored "-Wsign-conversion"
 #pragma GCC diagnostic ignored "-Wpointer-sign"
 #pragma GCC diagnostic ignored "-Wunused-variable"
 #pragma GCC diagnostic ignored "-Wunused-but-set-variable"
 #pragma GCC diagnostic ignored "-Wunused-function"
#endif

#include "hash.h"

// generated by genlex
#include "tok.h"
#include "lexdef.h"

static bool verbose;

enum Diatag {
  Dia_trc_state1,Dia_trc_tk1,
  Diatag_count };

static ub2 dialvls[Diatag_count] = { 1,1 };

static const char *dianames[Diatag_count] = {
  "trace-state",
  "trace-token"
};

struct diamod dia_lex = { dianames,dialvls,Diatag_count };

#define Slitint 256

#ifdef Lang_stresc
enum Esc { Esc_inv,Esc_nl,Esc_o,Esc_x,Esc_u,Esc_U,Esc_N,Esc_a=7,Esc_b,Esc_t,Esc_n,Esc_v,Esc_f,Esc_r };

static const enum Esc esctab[128] = {
  ['\n'] = Esc_nl,
  ['0'] = Esc_o, ['1'] = Esc_o, ['2'] = Esc_o, ['3'] = Esc_o, ['4'] = Esc_o, ['5'] = Esc_o, ['6'] = Esc_o, ['7'] = Esc_o,
  ['t'] = Esc_t,
  ['n'] = Esc_n,
  ['r'] = Esc_r,
  ['v'] = Esc_v,
  ['a'] = Esc_a,
  ['x'] = Esc_x,
  ['u'] = Esc_u, ['U'] = Esc_U,
  ['N'] = Esc_N
};
#endif

#undef ice
#define ice(fpos,fmt,...) lxice(FLN,fpos,fmt,__VA_ARGS__)

static Noret void __attribute__ ((format (printf,3,4))) lxice(ub4 fln,ub4 fpos,const char *fmt, ...)
{
  va_list ap;

  if (fpos == 0) fpos = hi32;

  va_start(ap, fmt);
  vmsgps(fln,Fatal,fpos,fmt,ap,"ice "," : exiting");
  va_end(ap);
  doexit(1);
}

// #define serxp(fpos,st,sln,c) serxpfln(FLN,fpos,st,sln,c)

// #define strc(tag,fpos,fmt,...) strcfln(FLN,tag,fpos,fmt,__VA_ARGS__)
// #define sdiag(tag,def,fpos,fmt,...) sdiagfln(FLN,tag,def,fpos,fmt,__VA_ARGS__)

static ub1 pass;
static cchar *srcnam;

#if 0
#define memcpy(d,s,n) mymemcpy(d,s,n)
#define memcmp(d,s,n) mymemcmp(d,s,n)

static void mymemcpy(char * restrict d,cchar * restrict s,ub2 n)
{
  switch(n) {
  case 1: *d = *s; return;
  case 2: *d = *s; d[1] = s[1]; return;
  case 3: *d = *s; d[1] = s[1]; d[2] = s[2]; return;
  }
  do *d++ = *s++; while (--n);
}

static ub1 mymemcmp(const ub1 * restrict d,const ub1 * restrict s,ub2 n)
{
  ub2 n4;
  const ub4 * restrict s4;
  const ub4 * restrict d4;

  switch(n) {
  case 1: return *d - *s;
  case 2: return (*d - *s) | (d[1] - s[1]);
  case 3: return (*d - *s) | (d[1] - s[1]) | (d[2] - s[2]);
  case 4: return *(ub4 *)d - *(ub4 *)s;
  }
  s4 = (ub4 *)s;
  d4 = (ub4 *)d;
  n4 = n >> 2;
  do {
    if (*d4 != *s4) return 1;
    d4++; s4++;
  } while (--n4);
  n &= 3;
  if (n == 0) return 0;
  d = (const ub1 * restrict)d4; s = (const ub1 * restrict)s4;
  do {
    if (*d != *s) return 1;
    d++; s++;
  } while (--n);
  return 0;
}

static ub4 align4(ub4 x,ub4 a)
{
  ub4 r;

  r = x & ~(a-1);

  return (r == x ? r : r + a);
}
#endif

static inline ub4 align4(ub4 x)
{
  return x + 4 - (x & 3);
}

static cchar *tknam(enum Token tk)
{
  ub2 len;
  ub1 hc;
  static char basbuf[4 * 16];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 16;
  bufno = (bufno + 1) & 3;

  char *p,*q;

  if (tk >= T99_count) return "*inv*";
#if Kwcnt > 0
  else if (tk < T99_kwd) { memcpy(buf,kwnampool + kwnamposs[tk],len=kwnamlens[tk]); buf[len] = 0; }
#endif
  else {
    tk -= T99_kwd;
    hc = tokhrctl[tk] & 0xf;
    if (hc == 0) return toknampool + toknampos[tk];
    len = tk * 4;
    p = hrtoknams + len;
    q = buf;
    while (hc--) *q++ = *p++;
    *q = 0;
  }
  return buf;
}

static Noret void lxerror(ub4 ln,ub4 col,ub2 specln,char c,enum Lxerror ec)
{
  char buf[1024];
  ub4 pos=0,blen = 1024;
  cchar *es = "";

  switch (ec) {
#ifdef Lxercnt
  case Lxe_str_nl: es = "newline in string"; break;
#endif
  case Lxe_count: break;
  }

  if (pass == 2) pos = mysnprintf(buf,0,blen,"pass 2 ");

  pos += mysnprintf(buf,pos,blen,"unexpected chr '%s' : %s",chprint(c),es);
  if (verbose) pos += mysnprintf(buf,pos,blen," %s.%u",specnam,specln);

  vpmsg(FLN,Fatal,srcnam,ln,col,buf,nil,nil);
  doexit(1);
}

#ifdef __clang__
  __attribute__((no_sanitize("unsigned-integer-overflow")) )
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wcast-align"
#endif

static inline bool samestr1(const ub1 *p,ub4 a,ub4 b,ub2 n)
{
  ub4 n4 = n >> 2;
  const ub4 *pa = (const ub4 *)(p + a);
  const ub4 *pb = (const ub4 *)(p + b);

  if (n4) {
    p += (n4 << 2);
    do {
      if (*pa != *pb) return 0;
      pa++; pb++;
    } while (--n4);
  }
  switch (n & 3) {
  case 0: return 1;
  case 1: return p[a] == p[b];
  case 2: return p[a] == p[b] && p[a+1] == p[b+1];
  case 3: return p[a] == p[b] && p[a+1] == p[b+1]  && p[a+2] == p[b+2];
  }
  return 0;
}

static inline bool samestr(const ub1 *a,const ub1 *b,ub2 n)
{
  ub2 i,n4 = n >> 2;
  const ub4 *a4 = (const ub4 *)a;
  const ub4 *b4 = (const ub4 *)b;

  if (n4) {
    i = 0;
    do {
      if (a4[i] != b4[i]) return 0;
    } while (++i < n4);
  }
  i = (n4 << 2);
  switch (n & 3) {
  case 0: return 1;
  case 1: return a[i] == b[i];
  case 2: return a[i] == b[i] && a[i+1] == b[i+1];
  case 3: return a[i] == b[i] && a[i+1] == b[i+1]  && a[i+2] == b[i+2];
  }
  return 0;
}

#ifdef __clang__
  #pragma clang diagnostic pop
#endif

#if 0
static bool memeq(cchar *p,cchar *q,ub2 len)
{
  ub2 i = 0;
  while (i < len && p[i] == q[i]) i++;
  return i == len;
}
#endif

static bool tracestate;
static bool tracetok;

#ifdef Addtrace
static void dotracestate(cchar *st,ub4 n,ub1 c,ub4 ln)
{
  infofln(ln | (Shsrc_lex1 << 16),"%3u state %s chr '%s'",n,st,chprint(c));
}

static void dotracetok(cchar *tk,ub4 n,ub4 ln)
{
  infofln(ln | (Shsrc_lex1 << 16),"%3u tk %s",n,tk);
}

static void dotracetok2(ub2 ln,ub2 tk,ub4 n,ub4 fln)
{
  infofln(fln | (Shsrc_lex1 << 16),"%3u %3u tk %s",ln,n,tknam(tk));
}
#endif

/*
  token bits

  lits  ifs.2 bits.30
        int   bin.1
              bin   hi.1  val:28  hi=hi32
              asc   pos.29
        flt   bin.1 c.1
              bin        mnt.22 exp.6
              asc        pos.28
        str   f.1 pos.30
 */

// todo static to local

// string lits
static ub4 slit0cnt,slit1cnt,slit2cnt,slit3cnt,slitxcnt,slitlimcnt;
static ub4 slitpos,slittop;
static ub4 slitucnt;

static ub4 *slithsh;
static ub4 slithshlen,slithshmask,slithshcnt;
static ub1 slithshbit;

static ub8 *slitids;

// int lits
static ub4 ilitcnt,ilit1cnt;
static ub4 nlitpos=0,nlittop;
static ub1 *nlitpool;

static ub4 flitpos;

// idents
static ub4 uidcnt,uid1cnt,uid2cnt;
static ub4 idsketch;

static ub4 idtablen;
static ub4 *idtab;
static ub4 *idntab;
static ub4 idnampos;
static ub1 *idnampool;

static ub4 *idhsh;
static ub4 idhshlen,idhshmask,idhshcnt,idhshmis;
static ub4 idnmax;
static ub1 idhshbit;

static void mkidhash(ub4 estcnt,ub4 cnt)
{
  ub4 hlen;
  ub4 bit = 0;

  idhshcnt = 0;

  if (estcnt > cnt) estcnt = cnt;
  else if (estcnt < 128) estcnt = 128;
  if (cnt < 16) hlen = cnt+4;
  else if (estcnt > hi24) {
    warning("estimated unique ID count %u`",estcnt);
    estcnt = min(estcnt,hi28);
    hlen = estcnt * 4;
  } else hlen = estcnt * 16;

  idhshlen = 1;
  while (idhshlen < hlen) { idhshlen <<= 1; bit++; }
  idhshmask = idhshlen-1;
  idhshbit = bit;

  hlen = idhshlen;
  idhsh = alloc(hlen,ub4,0,"lex id hash",nextcnt);
  info("%u entry id hash from u/id %u/%u",idhshlen,estcnt,cnt);
}

static ub4 idcheck(ub4 nam,ub2 len,ub4 v)
{
  ub4 x = idhsh[v];
  ub4 np,id;

  if (x == 0) { // slot free
    id = uidcnt++;
    if (id >= idtablen) ice(hi32,"id '%.*s' exceeds %u",len,idnampool+nam,id);
    idhsh[v] = id;
    np = idnampos;
//    vrb("add '%s'",idnampool+idnampos);
    idnampos = align4(nam + 1);
    idhshcnt++;
    if (len > idnmax) idnmax = len;
    idtab[id] = np;
    info("add id %u nid %u",id,np);
    return id; // new
  } else {
    np = idtab[x];
    if (samestr1(idnampool,np,idnampos,len)) return x; // existing: common
    else {
      idhshmis++;
      return hi32;
    }
  }
}

// get or if none insert id. returns idnid.idid
static ub4 idgetadd(ub4 nam,ub4 hc)
{
  ub4 v,v0;
  ub4 x;
  ub4 hc2;
  ub2 len = nam - idnampos;

  hc = (hc >> idhshbit) ^ hc;
  v = hc & idhshmask;

  idnampool[nam] = 0;

  x = idcheck(nam,len,v);
  if (x != hi32) return x;
  else { // probe once with second hash
    hc2 = hc >> idhshbit;
    v += hc2 & idhshmask;
    if (v >= idhshlen) v -= idhshlen;
    x = idcheck(nam,len,v);
    if (x != hi32) return x;
    else {
      v0 = v;
      do { // linear
        v = (v + 1) & idhshmask;
        x = idcheck(nam,len,v);
        if (x != hi32) return x;
      } while (v != v0);
      ice(0,"TODO resize id hash table overflow at %u of %u",idhshcnt,idhshlen);
    }
  }
}

static ub2 *id2tab;
static ub2 *id2nams;
static ub1 id2ch1map[256];
static ub1 id2ch1imp[256];
static ub1 id2ch2map[256];
static ub1 id2ch2imp[256];
static ub1 id2chr[256];
static ub1 id2nch1,id2nch2,id2shift1,id2shift2;
static ub2 id2mask1,id2mask2;

static ub2 id2getadd(ub1 c1,ub1 c2)
{
  ub1 a = id2ch1map[c1];
  ub1 b = id2ch2map[c2];
  ub2 id;
  ub2 ndx;

  if (a == 0xff || b == 0xff) ice(0,"invalid id2 '%s' '%s'",chprint(c1),chprint(c2));
  ndx = (a << id2shift1) + b;
  id = id2tab[ndx];
  if (id != hi16) {
    return id;
  }
  id2tab[ndx] = uid2cnt;
  id2nams[uid2cnt] = ndx;
  return uid2cnt++;
}

static ub1 id1tab[256];
static ub1 id1inv[256];

static ub1 id1getadd(ub1 c)
{
  ub1 id = id1tab[c];

  if (id == 0xff) {
    id = uid1cnt++;
    id1tab[c] = id;
    id1inv[id] = c;
  }
  return id;
}

static void id2nam(ub2 id,ub1 *dst)
{
  ub2 ndx = id2nams[id];
  ub2 a,b;

  a = ndx >> id2shift1;
  b = ndx & id2mask1;

  dst[0] = id2ch1imp[a];
  dst[1] = id2ch2imp[b];
  dst[2] = 0;
}

static ub1 *idnnam(ub4 id)
{
  ub4 nid = idtab[id];
  info("id %u nid %u",id,nid);
  return idnampool + nid;
}

ub1 *idnam(ub4 id)
{
  ub4 nid;
  ub2 x2;
  static ub1 buf[4];

  if (id < uid1cnt) { *buf = id1inv[id]; buf[1] = 0; return buf; }
  else if (id < uid2cnt) { id2nam(id - uid1cnt,buf); return buf; }
  else return idnnam(id - uid1cnt - uid2cnt);
}

static void mkid2tab(void) {
  ub2 c;
  ub2 n1=0,n2=0;
  ub1 x;

  for (c = 0; c < 256; c++) {
    id2ch1map[c] = 0xff;
    id2ch2map[c] = 0xff;
    x = id2chr[c];
    if (x & 1) { id2ch1map[c] = n1; id2ch1imp[n1++] = c; }
    if (x & 2) { id2ch2map[c] = n2; id2ch2imp[n2++] = c; }
  }
  vrb("id2map %u,%u",n1,n2);
  if ( (n1 | n2) == 0) return;
  id2nch1 = nxpwr2(n1,&id2shift1);
  id2nch2 = nxpwr2(n2,&id2shift2);
  id2mask1 = id2nch1-1;
  id2mask2 = id2nch2-1;
  id2tab = (ub2 *)minalloc(id2nch1 * id2nch2 * 2,2,0xff,"lex id2tab");
  id2nams = (ub2 *)minalloc(id2nch1 * id2nch2 * 2,2,Mnofil,"lex id2nam");
}

static void mkslithash(ub4 cnt)
{
  ub4 hlen;
  ub4 bit = 0;

  if (cnt < 16) hlen = cnt+8;
  else if (cnt > hi20) {
    warning("string lit count %u`",cnt);
    cnt = hi20;
    hlen = cnt * 4;
  } else hlen = cnt * 8;

  slithshlen = 1;
  while (slithshlen < hlen) { slithshlen <<= 1; bit++; }
  slithshmask = slithshlen-1;
  slithshbit = bit;

  slithsh = alloc(slithshlen,ub4,0,"lex slit hash",nextcnt);
  info("%u entry slit hash",slithshlen);
}

static ub4 slitcheck(ub1 *pool,ub4 nam0,ub4 nam1,ub4 v)
{
  ub4 x,np,id;
  ub4 l1,len = nam1 - nam0;

  if (v >= slithshlen) ice(0,"slit ndx %u above %u for %.*s",v,slithshlen,len,pool+nam0);

  x = slithsh[v];

  if (x == 0) { // slot free - consolidate pool
    id = slitucnt++;
    slithsh[v] = id;
    np = slitpos;
    // info("v %u x %u nam0 %u top %u",v,x,nam0,slittop);
    slitpos = align4(nam1 + 1);
    slithshcnt++;
    slitids[id] = np | ((ub8)len << 32);
    vrb("add slit len %u '%.*s' at %u",len,min(len,80),pool+nam0,nam0);
    return id; // new

  } else {
    l1 = slitids[x] >> 32;
    np = slitids[x] & hi32;
    // info("v %u x %u nam0 %u top %u",v,x,nam0,slittop);
    if (l1 == len && memcmp(pool + np,pool + nam0,len) == 0) return x;
    else return 0;
  }
}

// get or if none insert
static ub4 slitgetadd(ub1 *pool,ub4 nam1)
{
  ub4 nam0 = slitpos;
  ub4 len = nam1 - nam0;
  ub4 v;
  ub4 x,id;
  ub4 hc,hc2;
  ub2 lim;

  pool[nam1] = 0;

  if (len >= Slitint) {
    slitpos = align4(nam1 + 1);
    id = slitucnt++;
    slitids[id] = nam0 | ((ub8)len << 32);
    return id;
  }

  hc = hashalstr(pool+nam0,len,Hshseed);

  hc = (hc >> slithshbit) ^ hc;
  v = hc & slithshmask;

  x = slitcheck(pool,nam0,nam1,v);
  if (x) return x;
  else { // probe once with second hash
    hc2 = hc >> slithshbit;
    v += hc2 & slithshmask;
    if (v >= slithshlen) v -= slithshlen;
    x = slitcheck(pool,nam0,nam1,v);
    if (x) return x;
    else {
      lim=4;
      do { // linear
        v = (v + 1) & slithshmask;
        x = slitcheck(pool,nam0,nam1,v);
        if (x) return x;
      } while (--lim);
      slitpos = align4(nam1 + 1); // skip dedup
      id = slitucnt++;
      slitids[id] = nam0 | ((ub8)len << 32);
      return id;
    }
  }
}

#if Kwcnt > 0
static inline enum token lookupkw(ub1 len,ub4 hc)
{
  ub1 x,m;
  ub4 ndx;
  enum token kw;
  const ub1 *nam = idnampool+idnampos;

  if (len > hikwlen) return t99_count;
  else if (len >= mikwlen) m = 0xf0;
  else m = 0xf;

  x = kwhshlut[hc & 0xff]
      | kwhshlut[(hc >> 8) & 0xff]
      | kwhshlut[(hc >> 16) & 0xff]
      | kwhshlut[hc >> 24];

  if ( (x & m) != m) return t99_count;

  ndx = (hc >> Kwhshbit) ^ hc;
  kw = kwhsh[ndx & Kwhshmask];
  if (kw == t99_count) return t99_count;

  if (tkwnamlens[kw] == len && samestr(nam,tkwnampool + tkwnamposs[kw],len)) return kw;
  else return t99_count;
}
#endif

#ifdef Bltcnt
static inline enum Bltin lookupblt(ub1 len,ub4 hc)
{
  ub1 ndx,x,m;
  enum Bltin bt;
  const ub1 *nam = idnampool+idnampos;

  if (len >= hibltlen) return B99_count;

  ndx = (hc >> Blthshbit) ^ hc;

  bt = blthsh[ndx & Blthshmask];
  if (bt == B99_count) return B99_count;

  if (len >= mibltlen) m = 0xf0;
  else m = 0xf;

  x = blthshlut[hc & 0xff]
      | blthshlut[(hc >> 8) & 0xff]
      | blthshlut[(hc >> 16) & 0xff]
      | blthshlut[hc >> 24];

  if ( (x & m) != m) return B99_count;

  if (bltnamlens[bt] == len && samestr(nam,bltnampool + bltnamposs[bt],len)) return bt;
  else return B99_count;
}
#else
  #define lookupblt(len,hc) B99_count
#endif

#ifdef Duncnt
static inline enum Dunder lookupdun(ub1 len,ub4 hc)
{
  ub1 ndx,x,m;
  enum Dunder dun;
  const ub1 *nam = idnampool+idnampos;

  if (len >= hidunlen) return D99_count;

  hc = (hc >> Dunhshbit) ^ hc;

  ndx = (hc >> Hshdshift) & Dunhshmask;
  dun = dunhsh[ndx];
  if (dun == D99_count) return D99_count;

  if (dunnamlens[dun] == len && samestr(nam,dunnampool + dunnamposs[dun],len)) return dun;
  else return D99_count;
}
#else
  #define lookupdun(len,hc) D99_count
#endif

// cs.princeton.edu/~rs/talks/AC11-Cardinality.pdf  philippe flajolet / martin '85
static inline void exp_first0(ub4 x)
{
  idsketch |= ~x & (x+1);
}

static ub4 exp_est(void)
{
  ub4 x = ~idsketch & (idsketch+1);

  return x + (x >> 1);
}

static int tryopen(cchar *dir,cchar *name,bool need)
{
  char path[Pathname];
  cchar *p;
  int fd;

  if (dir == nil || *dir == 0 || (dir[0] == '.' && dir[1] == '/') ) p = name;
  else {
    mysnprintf(path,0,Pathname,"%s/%s",dir,name);
    p = path;
  }

  if (osopenseq(p,&fd) && need) oserror("cannot open %s",p);
  return fd;
}

#ifdef Lang_stresc
static ub1 lxatox1(ub1 c)
{
  ub1 x;

  if (c >= '0' && c <= '9') x = c - '0';
  else if (c >= 'A') x = (c | 0x20) - 'a' + 10;
  else return 0xff;
  return x;
}

static ub1 doesco(const ub1 * restrict src,ub4 sn)
{
  ub1 nc,x1,c = src[sn];

  x1 = c - '0';
  nc = src[sn+1]; if (nc >= '0' && nc < '8') x1 = x1 << 3 | (nc - '0');
  nc = src[sn+2]; if (nc >= '0' && nc < '8') x1 = x1 << 3 | (nc - '0');
  return x1;
}

static ub1 doescx(const ub1 * restrict src,ub4 sn)
{
  ub1 x1,x2,c = src[sn],d = src[sn+1];

  x1 = lxatox1(c);
  x2 = lxatox1(d);

  if ( (x1 | x2) > 0xf) serror(0,"illegal hex escape seq '%s%s'",chprint(c),chprint(d));
  return x1 << 4 | x2;
}

static ub4 doescu(const ub1 * restrict src,ub4 sn,ub1 *pool,ub4 *plitx,ub1 ctl)
{
  ub4 litx = *plitx;

  pool[litx] = *src;
  switch(ctl) {
  case 'U': serror(sn,"\\Uxx.. in  string lits at pos %u TODO",litx);
  case 'u': serror(sn,"\\uxx.. in  string lits at pos %u TODO",litx);
  case 'N': serror(sn,"\\N{..} in  string lits at pos %u TODO",litx);
  }
  return sn+1;
}
#endif

#define Dent 256

enum Slitctl { Slit_none,Slit_f=1,Slit_r=2,Slit_l=4,Slit_b=8,Slit_u=16 };

#define B32max (1U << 30)
#define X32max 0xfffffff
#define D32max (1U << 28)
#define E16max 0xff

static ub4 tkstats[T99_count];

static void doemit(struct lexsyn *lsp,cchar *name)
{
  const enum Token *tks = lsp->toks;
  const ub1 *atrs = lsp->atrs;
  const ub8 *bits = lsp->bits;
  const ub2 *dfps = lsp->dfps;
  ub4 tkcnt = lsp->tkcnt;
  const ub1 *slitpool = lsp->slitpool;

  bool emit = (globs.emit & Lexpas);
  enum Token tk=0;
  ub1 atr;
  ub4 dn,bn=0;
  ub8 x8=0;
  ub4 x4,np;
  ub2 x2;
  ub2 dfp;
  ub4 fpos=0;
  ub4 pos;
  ub4 l1,len,blen = 256;
  char buf[256];
  char sbuf[8];
  cchar *str;

  if (emit) msglog(name,"tks","lex");
  for (dn = 0; dn < tkcnt; dn++) {
    tk = tks[dn];
    atr = atrs[dn];
    dfp = dfps[dn];
    fpos += dfp;
    if (tk >= T99_count) ice(fpos,"invalid token %u",tk);
    pos = mysnprintf(buf,0,blen,"%3u %-10s",dn,tknam(tk));

#ifdef Emitdetail
    switch (tk) {
    case Tid:   if (atr < Idlen_2) {
                  buf[pos++] = id1inv[atr];
                } else {
                  x8 = bits[bn++];
                  if (atr == Idlen_n) pos += mysnprintf(buf,pos,blen,"%s",idnnam(x8));
                  else { id2nam(x8,buf + pos); pos += 2; }
                }
                break;
    case Tnlit: if (atr < 10) buf[pos++] = atr + '0';
                else if (atr < Ilit4) pos += mysnprintf(buf,pos,blen,"%u",atr);
                else {
                  x4 = bits[bn++];
                  if (atr == Ilit4) pos += mysnprintf(buf,pos,blen,"%u",x4);
                  else if (atr == Flit8) pos += mysnprintf(buf,pos,blen,"flt %x",x4);
                  else if (atr >= Ilita) pos += mysnprintf(buf,pos,blen,"%s",nlitpool + x4);
                }
                break;
    case Tslit: if (atr < Slit_len) pos += mysnprintf(buf,pos,blen,"'%s'",chprint(atr));
                else {
                  x4 = bits[bn++];
                  len = atr & ~Slit_len;
                  if (len > 3) {
                    l1 = slitids[x4] >> 32;
                    np = slitids[x4] & hi32;
                    str = chprintn(slitpool + np,min(l1,32));
                  } else {
                    *(ub4 *)sbuf = x4;
                    buf[pos++] = sbuf[0];
                    buf[pos++] = sbuf[1];
                    if (len == 3) buf[pos++] = sbuf[2];
                    buf[pos] = 0;
                    str = chprintn(sbuf,len);
                  }
                  pos += mysnprintf(buf,pos,blen,"%3x.%u '%s'",x4,len,str);
                }
                break;
    default:    break;
    }
#endif
    sinfo(fpos,"%.*s",pos,buf);
  }
  if (emit) msglog(nil,nil,nil);
}

#define setfpos(dn,n) dfps[dn] = n - prvfp; prvfp = n;

static int lex(struct fnaminf *mf,const unsigned char * restrict sp,ub4 slen,struct lexsyn *lsp,ub8 T0)
{
  int rv = 0;
  ub4 len;

  enum Slitctl slitctl=0,fstrctl=0;
  bool litbin = 1;
  bool litfpi=0;

  // tokens
  enum Token tk=0;
  enum Bltin blt;
  enum Dunder dun;
  ub4 tkcnt=0;
  void *tkbas=nil;
  ub1 *tks=nil;
  ub1 *atrs=nil;
  ub8 *bits=nil;
  ub2 *dfps=nil;
  struct mempart tkpart[4];

  ub4 tkgrps[Tkgrp];
  ub1 grp;

  // str lits
  ub1 *slitpool=nil;
  ub4 slitx=0;
  ub4 idxpos=0;

  // indent
  static ub2 dentst[Dent];
  ub2 dent;
  ub2 dentlvl=0;

  // braces
  ub4 bolvls[Depth];
  ub1 bolvlc[Depth];
  ub2 bolvl=0;

// line/col/dent
  ub4 l=0;
  ub4 nlcol=0;
  ub4 *lntab=nil;
  ub4 lncnt;
  bool hasdent;

  ub4 cnt;

  ub8 T1=T0;

  timeit(&T1,nil);

  ub1 c,prvc1,prvc2;
  ub4 dn = 0,bn = 0;
  ub4 n = 0, prvfp = 0;

  ub4 idnplen=0;

  // idents
  ub4 idcnt=0,id1cnt=0,id2cnt=0;

  // kwd, bltin, dunder
  ub4 kwcnt=0;
  ub4 bltcnt=0;
  ub4 duncnt=0;

  // str lits
  ub4 slitcnt=0;

  // flt lits
  ub4 flitcnt=0;

  nlitpos=0;
  flitpos=0;

  dentlvl=0;
  dentst[0] = 0;

  idsketch = 0;

  memset(id2chr,0,256);

  ub1 t=0,u;

  ub1 Q = 0;
  ub4 N = 0;
  ub1 R0 = 0;
  ub1 sign = 0;

  ub4 id=0;
  ub1 x1;
  ub4 x4;
  ub8 x8;

  ub4 hc=0;

  // nlit
  ub4 u4v=0;

  // flit
  ub4 fdp=0; // dot pos
  ub2 fxp=0; // e+nn
  bool fxs=0;

  // f-strings
  ub1 fstrco=0;
  ub1 fstrQ=0;

  enum Token kwd;
  enum token kw;
  ub4 idhilen = 0;

  memset(tkgrps,0,sizeof(tkgrps));
  memset(bolvlc,0,Depth);

  pass = 1;

  if (slen > 3 && sp[0] == '#' && sp[1] == '!') { // skip shebang
    n += 2;
    while(n < slen && sp[n] != '\n') n++;
  }

  infofln(FLN,"+lex1");

#undef  FLN
#define FLN __LINE__|(Shsrc_lex1<<16)

#include "lextb1.i"

#undef  FLN
#define FLN __LINE__|(msgfile<<16)

  infofln(FLN,"-lex1");

  if (dn == 0) {
    info("%s is empty",lsp->name);
    return 0;
  }

  tkcnt = dn;
  showcnt("x token",tkcnt);
  showcnt("line",l);
  lncnt = l;

  if (verbose) timeit2(&T1,slen,"pass 1 tokenised ` in");

  showcnt("2int n lit",ilit1cnt);
  showcnt("2int 1 lit",ilitcnt);
  showcnt("2flt lit",flitcnt);

  showcnt("2str n lit",slitcnt);
  showcnt("2str 0 lit",slit0cnt);
  showcnt("2str 1 lit",slit1cnt);
  showcnt("2str 2 lit",slit2cnt);
  showcnt("2str 3 lit",slit3cnt);
  showcnt("2str x lit",slitxcnt);

  if (slitcnt) mkslithash(slitcnt);

  slitcnt += slit1cnt + slit2cnt + slit3cnt + slitxcnt;

  if (slitcnt) {
    slitpos += 5 * (slitcnt+2); // align + 0-term
    showsiz("slit pool",slitpos);
    slitids = alloc(slitcnt,ub8,Mnofil,"lex slit ids",nextcnt);
  }
  slitcnt += slit0cnt;
  showcnt("2str n lit",slitcnt);

  if (idcnt) {
    showcnt("2ident / kwd",idcnt);
    if (idnplen >= Idpool) ice(n,"ID literal pool exceeds max %u`B",Idpool);
    info("idpool %u`B max len %u",idnplen,idhilen);
    idnplen += 5 * (idcnt+1); // align + 0-term
  }

  if (tkcnt >= Tokencnt) serror(n,"token count %u exceeds limit %u",tkcnt,Tokencnt);

  ub4 bitcnt = ilitcnt + flitcnt + slitcnt + slit2cnt + slit3cnt + slitxcnt;
  bitcnt += idcnt + id2cnt;

  ub4 xcnt = slit0cnt + slit1cnt + id1cnt + ilit1cnt;

  tkgrps[0] += bitcnt + xcnt;
  tkcnt += bitcnt + xcnt;

  showcnt("2ident2",id2cnt);
  showcnt("2ident1",id1cnt);

  showcnt("2token",tkcnt);

  if (tkcnt >= Tokencnt) serror(n,"token count %u exceeds limit %u",tkcnt,Tokencnt);

  uidcnt = exp_est();
  if (idcnt == 0) uidcnt = 0;

  showcnt("2est unique ident",uidcnt);

  showsiz("nlit pool",nlitpos);

  if (globs.rununtil == 2) { infofln(FLN,"until lex pass 1"); return 0; }

  tkpart[1].nel = tkpart[2].nel = tkpart[3].nel = tkcnt+Tkpad;
  tkpart[1].siz = 2;
  tkpart[2].siz = 1;
  tkpart[3].siz = 1;

  tkpart[0].siz = 8;
  tkpart[0].nel = xcnt;

  tkbas = allocset(tkpart,4,Mnofil,"lex tokens",nextcnt);
  bits = tkpart[0].ptr;
  dfps = tkpart[1].ptr;
  tks = tkpart[2].ptr;
  atrs = tkpart[3].ptr;

  if (tkpart[0].ismmap == 0) memset(atrs,0,tkcnt);

  nlittop = nlitpos; nlitpos = 0;
  if (nlittop) {
    nlitpool = alloc(nlittop,ub1,Mnofil,"lex nlit pool",nextcnt);
  }

  slittop = slitpos;
  if (slitpos) {
    slittop += 2;
    slitpool = alloc(slittop,ub1,Mnofil,"lex slit pool",nextcnt);
  }

  if (idnplen) idnampool = alloc(idnplen+4,ub1,Mnofil,"lex idnpool",nextcnt);
  idnampos = 4;

  if (idcnt) {
    mkidhash(uidcnt,idcnt);
    idtablen = uidcnt * 2 + 1024;
    idtab = alloc(idtablen,ub4,Mnofil,"lex id tab",nextcnt);
  }
  if (id2cnt) {
    mkid2tab();
  }
  memset(id1tab,0xff,256);

  slitpos = 4;

  lncnt += 2;
  lntab = lncnt < 1024 ? minalloc(lncnt * 4,4,Mnofil,"lex lntab") : medalloc(lncnt * 4,4,"lex lntab");

  setsrcmfile(mf,lntab,lncnt,n);

  n = 0;
  dn = bn = 0;
  l = 0;

  fxp = 0;
  fdp = 0;

  fstrco=0;
  fstrQ=0;

  dentlvl=0;
  dentst[0] = 0;

  idcnt = id1cnt = id2cnt = 0;

  pass = 2;

  infofln(FLN,"+lex2");

#undef  FLN
#define FLN __LINE__|(Shsrc_lex2<<16)

#include "lextb2.i"

#undef  FLN
#define FLN __LINE__|(msgfile<<16)

  infofln(FLN,"-lex2");

  if (verbose) timeit2(&T1,slen,"pass 2 tokenised `B in");

  showcnt("3token",tkcnt);
  showcnt("3line",l);

  showcnt("bltin",bltcnt);
  showcnt("dunder",duncnt);

  if (idhshcnt) {
    info("%3u` uniq idents max len %u",idhshcnt,idnmax);
    info("id hash table used %u` of %u` retry %u`",idhshcnt,idhshlen,idhshmis);
  }
  showcnt("3ident2",id2cnt);

  if (slithshcnt) {
    showcnt("3uniq slit",slithshcnt);
    showcnt("3uniq slit",slitucnt);
    info("slit hash table used %u` of %u`, skipped %u`",slithshcnt,slithshlen,slitlimcnt);
  }

  if (dn > tkcnt) {
    error("%u :1 vs %u :2 tokens dif %u",tkcnt,dn,dn - tkcnt);
    rv = 1;
  } else if (dn < tkcnt) {
    warning("%u :1 vs %u :2 tokens dif %u",tkcnt,dn,tkcnt - dn);
    rv = 0;
  }

  tkcnt = dn;

  lntab[l] = n;
  lntab[l+1] = n+1;

  memset(tks+tkcnt,T99_eof,Tkpad);

#if 0
  kwcnt = 0;
  for (dn = 0; dn < tkcnt; dn++) {
    tk = tks[dn];
    tkstats[tk]++;
  }
  for (tk = 0; tk < T99_count; tk++) {
    cnt = tkstats[tk];
    if (cnt) {
#if Kwcnt > 0
      if (tk < T99_kwd) kwcnt += cnt;
#endif
      info("%5u %s",cnt,tknam(tk));
    }
  }
  showcnt("kwd",kwcnt);
#endif

  for (grp = 0; grp < Tkgrp; grp++) {
    cnt = tkgrps[grp];
    if (cnt) info("grp %u %u",grp,cnt);
    if (grp < Tkgrps) lsp->tkgrps[grp] = cnt;
  }

  if (nlitpos == 0) { if (nlitpool) afree(nlitpool,"lex nlit pool",nextcnt); }
  else { lsp->nlitpool = nlitpool; lsp->nlittop = nlitpos; }
  lsp->nlitcnt = ilitcnt + flitcnt + ilit1cnt;

  if (slitxcnt) lsp->src = sp;

  showcnt("token",dn);

  lsp->tkcnt = dn;
  lsp->tbcnt = bn;

  lsp->toks = tks;
  lsp->bits = bits;
  lsp->atrs = atrs;
  lsp->dfps = dfps;

  lsp->idcnt = idcnt + id1cnt + id2cnt;
  lsp->uidcnt = uidcnt;
  lsp->uid1cnt = uid1cnt;
  lsp->uid2cnt = uid2cnt;

  lsp->idnampool = idnampool;

  lsp->slitpool = slitpool;
  lsp->slitcnt = slitcnt;
  lsp->slittop = slittop;

  lsp->tkbas = tkbas;

  memcpy(lsp->tkgrps,tkgrps,sizeof(tkgrps));

  if ( (globs.emit & 1) | (globs.log & 1) ) doemit(lsp,mf->name);

  if (bolvl) {
    sinfofln(hi32,bolvls[0],"opening '%c' here",bolvlc[0]);
    serror(n,"no matching '%c'",bolvlc[0]);
  }

  ub2 hidepth = (ub2)((ub1 *)memchr(bolvlc,0,Depth) - bolvlc);
  info("max depth %u",hidepth);
  lsp->hidepth = hidepth;

  if (idhsh) afree(idhsh,"lex id hash",nextcnt);

  if (globs.rununtil == 3) { infofln(FLN,"until lex"); return 0; }

  return rv;
}

int lexfile(ub4 fln,cchar *path,cchar *parpath,enum Inctype inc,struct lexsyn *lsp,ub8 T0)
{
  int rv;
  ub2 n = 0, dirsep = 0;
  char *ipath,*p;
  int fd = -1;
  struct fnaminf *fb;
  ub2 incdir=0;
  ub4 slen,xlen;
  ub4 nr;

  struct osstat ino;
  char chkpath[Pathname];

  ub8 T1=0;

  if (path == nil) { errorfln(FLN,fln,"nil file name for lex"); return 1; }
  else if (*path == 0) { errorfln(FLN,fln,"empty file name for lex"); return 1; }

  while (path[n]) { if (path[n] == '/') dirsep = n; n++; }
  if (n == dirsep + 1) { errorfln(FLN,fln,"lex: path '%s' is a directory",path); return 1; }

  timeit(&T1,nil);

  if (inc == Inone) {
    fd = tryopen(nil,path,1);
    if (fd == -1) return 1;
  } else if (inc == Iuser) { // search in dir of includer

    mysnprintf(chkpath,0,Pathname-2,"%.*s/%s",dirsep,parpath,path);
    fd = tryopen(nil,path,1);
    if (fd == -1) return 1;
  } else {

    while (fd == -1 && incdir < lsp->incdircnt) { // search in system dirs and -I
      mysnprintf(chkpath,0,Pathname-2,"%s/%s",lsp->incdirs[incdir],path);
      fd = tryopen(nil,chkpath,0);
      incdir++;
    }
    if (fd == -1) { errorfln(FLN,0,"cannot open %s",path); return hi32; }
  }

  if (osfdinfo(&ino,fd)) { osclose(fd); errorfln(FLN,0,"cannot get info for %s",path); return 1; }
//  if (ino.len >= (1U << 31)) { osclose(fd); errorfln(FLN,0,"%s length %lu exceeds %u",path,ino.len,1U << 31); return 1; }

  fb = getsrcmfile();

  fb->ino = ino.ino;
  fb->dev = ino.dev;

  if (chksrcmfile(fb)) {
    info("skip duplicate %s ",path);
    osclose(fd);
    return 0;
  }

  srcnam = path;

  slen = (ub4)ino.len;
  xlen = slen + max(Cclen+2,8); // pad with 0

  ub1 *sp;

  if (slen == 0) { info("%s is empty",path); osclose(fd); return 0; }
  sp = alloc(xlen,char,Mnofil,"lex file",nextcnt);
  memset(sp+slen,0,xlen-slen);

  memset(sp,0,slen);

  timeit(&T1,nil);

  rv = osread(fd,sp,slen,&nr);
  if (rv) {
    if (rv < 0) oserror("cannot read %s",path);
    else error("cannot read %s",path);
    osclose(fd);
    return 1;
  }
  osclose(fd);
//  if (nr != slen) { error("partial read %'uB of %'uB of %s",(ub4)nr,(ub4)slen,path); return 1; }

  ipath = minalloc(n+1,1,Mnofil,"lex inc path");
  memcpy(ipath,path,n);
  ipath[n] = 0;

  p = ipath + n;
  while (p > ipath && p[-1] != '/') p--;
  fb->name = p;
  fb->path = ipath;
  fb->dirsep = dirsep;
  fb->len = slen;
  fb->incdir = incdir;

  if (verbose) timeit2(&T1,slen,"read ` in");
  msgfls();

  srcnam = path + dirsep;

  lsp->srclen = slen;

  if (globs.rununtil == 1) { infofln(FLN,"until file"); return 0; }

  rv = lex(fb,sp,slen,lsp,T1);

  if (lsp->src == nil) afree(sp,"src",nextcnt);
  msgfls();

  if (rv || lsp->tkcnt == 0) return rv;

  timeit2(&T0,slen,"tokenised ` in");

  return 0;
}

int lexstr(const unsigned char * restrict str,ub2 slen,struct lexsyn *lsp,ub8 T0)
{
  ub8 T1 = T0;
  struct fnaminf *fb;
  int rv;

  fb = getsrcmfile();
  fb->path = "(cmdline)";

  fb->len = slen;
  rv = lex(fb,str,slen,lsp,T1);

  if (rv) return rv;

  timeit2(&T0,slen,"tokenised ` in");
  return 0;
}

cchar *lex_info(void) {
  return lexinfo;
}

void inilex(void)
{
  ub4 hc,i;

  verbose = globs.msglvl >= Vrb;

  tracestate = dialvls[Dia_trc_state1];
  tracetok = dialvls[Dia_trc_tk1];

#ifdef Addtrace
  if (tracestate) infofln(FLN,"state trace on");
  if (tracetok) infofln(FLN,"token trace on");
#endif

  sassert(sizeof(ctab) == 256,"short enums required");

  infofln(hi32,"%s\n",lexinfo);

  // check genlex used same hash as us
#if Kwcnt > 0
  i = sizeof(tkwnampool);
  hc = hashalstr(tkwnampool,i,Hshseed);
  if (hc != kwnamhsh) {
    ice(0,"lexer inconsistent kwd hash %s: %x versus genlex: %x len %u seed %x '%.*s'",globs.prgnam,hc,kwnamhsh,i,Hshseed,i,tkwnampool);
  }
#endif

  lastcnt
}
