/* lex.c - lexical analysis pass

   This file is part of Morelia, a subset of Python with emphasis on efficiency.

   Copyright © 2022 Joris van der Geer.

   Morelia is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Morelia is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program, typically in the file License.txt
   If not, see http://www.gnu.org/licenses.
 */

#include <stdarg.h>
#include <string.h>
#include <stdlib.h>

#include "base.h"
#include "chr.h"

#include "os.h"

#include "mem.h"

#include "fmt.h"

static ub4 msgfile = Shsrc_lex;
#include "msg.h"

#include "dia.h"

#include "util.h"

#include "lexsyn.h"

// max brackets nesting and indents
#define Depth 256

// max token stream len
#define Tokencnt (1U << 26)

#define Emitdetail

// #define Addtrace

#if defined __clang__
 #pragma clang diagnostic ignored "-Wsign-conversion"
 #pragma clang diagnostic ignored "-Wduplicate-enum"
 #pragma clang diagnostic ignored "-Wgnu-label-as-value"
#elif defined __GNUC__
 #pragma GCC diagnostic ignored "-Wsign-conversion"
 #pragma GCC diagnostic ignored "-Wpointer-sign"
 #pragma GCC diagnostic ignored "-Wunused-variable"
 #pragma GCC diagnostic ignored "-Wunused-but-set-variable"
 #pragma GCC diagnostic ignored "-Wunused-function"
#endif

#include "hash.h"

// generated by genlex
#include "tok.h"
#include "lexdef.h"

static bool verbose;

static bool lang_fstring = 0;
static bool lang_concat = 0;

static bool lang_mocklex = 0;

static char cursrc[256];

enum Diatag {
  Dia_trc_state1,Dia_trc_tk1,
  Diatag_count };

static ub2 dialvls[Diatag_count] = { 1,1 };

static const char *dianames[Diatag_count] = {
  "trace-state",
  "trace-token"
};

struct diamod dia_lex = { dianames,dialvls,Diatag_count };

#define Slitint 256

enum Packed8 Esc { Esc_inv,Esc_nl,Esc_o,Esc_x,Esc_u,Esc_U,Esc_N,Esc_a=7,Esc_b,Esc_t,Esc_n,Esc_v,Esc_f,Esc_r };

static const enum Esc esctab[128] = {
  ['\n'] = Esc_nl,
  ['\\'] = '\\',
  ['\''] = '\'',
  ['"'] = '"',
  ['0'] = Esc_o, ['1'] = Esc_o, ['2'] = Esc_o, ['3'] = Esc_o, ['4'] = Esc_o, ['5'] = Esc_o, ['6'] = Esc_o, ['7'] = Esc_o,
  ['f'] = Esc_f,
  ['t'] = Esc_t,
  ['n'] = Esc_n,
  ['r'] = Esc_r,
  ['v'] = Esc_v,
  ['a'] = Esc_a,
  ['b'] = Esc_b,
  ['x'] = Esc_x,
  ['u'] = Esc_u, ['U'] = Esc_U,
  ['N'] = Esc_N
};

#undef ice
#define ice(fpos,fmt,...) lxice(FLN,fpos,fmt,__VA_ARGS__)

static Noret void __attribute__ ((format (printf,3,4))) lxice(ub4 fln,ub4 fpos,const char *fmt, ...)
{
  va_list ap;

  if (fpos == 0) fpos = hi32;
  msglog(nil,nil,nil);

  va_start(ap, fmt);
  vmsgps(fln,Fatal,fpos,fmt,ap,"ice "," : exiting");
  va_end(ap);
  doexit(1);
}

// #define serxp(fpos,st,sln,c) serxpfln(FLN,fpos,st,sln,c)

// #define strc(tag,fpos,fmt,...) strcfln(FLN,tag,fpos,fmt,__VA_ARGS__)
// #define sdiag(tag,def,fpos,fmt,...) sdiagfln(FLN,tag,def,fpos,fmt,__VA_ARGS__)

static ub1 pass;
static cchar *srcnam;

static ub4 strlen4(cchar *s) { return (ub4)strlen(s); }

#if 0
#define memcpy(d,s,n) mymemcpy(d,s,n)
#define memcmp(d,s,n) mymemcmp(d,s,n)

static void mymemcpy(char * restrict d,cchar * restrict s,ub2 n)
{
  switch(n) {
  case 1: *d = *s; return;
  case 2: *d = *s; d[1] = s[1]; return;
  case 3: *d = *s; d[1] = s[1]; d[2] = s[2]; return;
  }
  do *d++ = *s++; while (--n);
}

static ub1 mymemcmp(const ub1 * restrict d,const ub1 * restrict s,ub2 n)
{
  ub2 n4;
  const ub4 * restrict s4;
  const ub4 * restrict d4;

  switch(n) {
  case 1: return *d - *s;
  case 2: return (*d - *s) | (d[1] - s[1]);
  case 3: return (*d - *s) | (d[1] - s[1]) | (d[2] - s[2]);
  case 4: return *(ub4 *)d - *(ub4 *)s;
  }
  s4 = (ub4 *)s;
  d4 = (ub4 *)d;
  n4 = n >> 2;
  do {
    if (*d4 != *s4) return 1;
    d4++; s4++;
  } while (--n4);
  n &= 3;
  if (n == 0) return 0;
  d = (const ub1 * restrict)d4; s = (const ub1 * restrict)s4;
  do {
    if (*d != *s) return 1;
    d++; s++;
  } while (--n);
  return 0;
}

static ub4 align4(ub4 x,ub4 a)
{
  ub4 r;

  r = x & ~(a-1);

  return (r == x ? r : r + a);
}
#endif

static inline ub4 align4(ub4 x)
{
  return x + 4 - (x & 3);
}

static cchar *tknam(enum Token tk)
{
  ub2 len;
  ub1 hc;
  static char basbuf[4 * 16];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 16;
  bufno = (bufno + 1) & 3;

  char *p,*q;

  if (tk >= T99_count) return "*inv*";
#if Kwcnt > 0
  else if (tk < T99_kwd) { memcpy(buf,kwnampool + kwnamposs[tk],len=kwnamlens[tk]); buf[len] = 0; }
#endif
  else {
    tk -= T99_kwd;
    hc = tokhrctl[tk] & 0xf;
    if (hc == 0) return toknampool + toknampos[tk];
    p = hrtoknams + tk * 4;
    q = buf;
    while (hc--) *q++ = *p++;
    *q = 0;
  }
  return buf;
}

static cchar *bltnam(enum Bltin blt,ub4 *plen)
{
  ub2 len=0;
  static char basbuf[4 * 16];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 16;
  bufno = (bufno + 1) & 3;

  blt = min(blt,B99_count);
#ifdef Bltcnt
  memcpy(buf,bltnampool + bltnamposs[dun],len=bltnamlens[dun]);
#endif
 buf[len] = 0;
 if (plen) *plen = len;
 return buf;
}

static cchar *dunnam(enum Dunder dun)
{
  ub2 len=0;
  static char basbuf[4 * 16];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 16;
  bufno = (bufno + 1) & 3;

  dun = min(dun,D99_count);
#ifdef Duncnt
  memcpy(buf,dunnampool + dunnamposs[dun],len=dunnamlens[dun]);
#endif
 buf[len] = 0;
 return buf;
}

static void lxdiag(enum Msglvl lvl,ub4 ln,ub4 col,ub4 stln,ub4 c,cchar *msg)
{
  char buf[1024];
  ub4 pos=0,blen = 1024;
  ub4 specln = stln & hi16;
  ub4 tabln = stln >> 16;

  if (pass == 2) pos = mysnprintf(buf,0,blen,"pass 2 ");
  if (verbose) pos += mysnprintf(buf,pos,blen,"%s.%u tbl %u ",specnam,specln,tabln);

  if (*cursrc) pos += mysnprintf(buf,pos,blen,"%s ",cursrc);
  pos += mysnprintf(buf,pos,blen,"at char '%s' : ",chprint(c));

  vpmsg(FLN,lvl,srcnam,ln+1,col+1,buf,nil,msg ? msg : "unexpected");
}

static Noret void lxerror(ub4 ln,ub4 col,ub4 stln,ub4 c,cchar *msg)
{
  lxdiag(Fatal,ln,col,stln,c,msg);
  doexit(1);
}

static void lxwarn(ub4 ln,ub4 col,ub2 stln,ub4 c,cchar *msg)
{
  lxdiag(Warn,ln,col,stln,c,msg);
}

#ifdef __clang__
  __attribute__((no_sanitize("unsigned-integer-overflow")) )
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wcast-align"
#endif

static inline bool samestr1(const ub1 *p,ub4 a,ub4 b,ub2 n)
{
  ub4 n4 = n >> 2;
  const ub4 *pa = (const ub4 *)(p + a);
  const ub4 *pb = (const ub4 *)(p + b);

  if (n4) {
    p += (n4 << 2);
    do {
      if (*pa != *pb) return 0;
      pa++; pb++;
    } while (--n4);
  }
  switch (n & 3) {
  case 0: return 1;
  case 1: return p[a] == p[b];
  case 2: return p[a] == p[b] && p[a+1] == p[b+1];
  case 3: return p[a] == p[b] && p[a+1] == p[b+1]  && p[a+2] == p[b+2];
  }
  return 0;
}

static inline bool samestr(const ub1 *a,const ub1 *b,ub2 n)
{
  ub2 i,n4 = n >> 2;
  const ub4 *a4 = (const ub4 *)a;
  const ub4 *b4 = (const ub4 *)b;

  if (n4) {
    i = 0;
    do {
      if (a4[i] != b4[i]) return 0;
    } while (++i < n4);
  }
  i = (n4 << 2);
  switch (n & 3) {
  case 0: return 1;
  case 1: return a[i] == b[i];
  case 2: return a[i] == b[i] && a[i+1] == b[i+1];
  case 3: return a[i] == b[i] && a[i+1] == b[i+1]  && a[i+2] == b[i+2];
  }
  return 0;
}

#ifdef __clang__
  #pragma clang diagnostic pop
#endif

#if 0
static bool memeq(cchar *p,cchar *q,ub2 len)
{
  ub2 i = 0;
  while (i < len && p[i] == q[i]) i++;
  return i == len;
}
#endif

static bool tracestate;
static bool tracetok;

#ifdef Addtrace
static void dotracestate(cchar *st,ub4 n,ub1 c,ub4 ln)
{
  infofln(ln | (Shsrc_lex1 << 16),"%3u state %s chr '%s'",n,st,chprint(c));
}

static void dotracetok(cchar *tk,ub4 n,ub4 ln)
{
  infofln(ln | (Shsrc_lex1 << 16),"%3u tk %s",n,tk);
}

static void dotracetok2(ub2 ln,ub2 tk,ub4 n,ub4 fln)
{
  infofln(fln | (Shsrc_lex1 << 16),"%3u %3u tk %s",ln,n,tknam(tk));
}
#endif

/*
  token bits

  lits  ifs.2 bits.30
        int   bin.1
              bin   hi.1  val:28  hi=hi32
              asc   pos.29
        flt   bin.1 c.1
              bin        mnt.22 exp.6
              asc        pos.28
        str   f.1 pos.30
 */

// todo static to local

// string lits
static ub4 slit0cnt,slit1cnt,slit2cnt,slit3cnt,slitxcnt,slitncnt,slitlimcnt;
static ub4 slitpos,slittop;
static ub4 slitucnt,slitidlen;

static ub4 *slithsh;
static ub4 slithshlen,slithshmask,slithshcnt,slithshmis;
static ub1 slithshbit;

static ub8 *slitids;

// idents
static ub4 uidcnt,uid1cnt,uid2cnt;

static ub4 idtablen;
static ub4 *idtab;
static ub4 *idntab;
static ub4 idnampos;
static ub1 *idnampool;

static ub4 *idhsh;
static ub4 idhshlen,idhshmask,idhshcnt,idhshmis;
static ub4 idnmax;
static ub1 idhshbit;

static void mkidhash(ub4 estcnt,ub4 cnt)
{
  ub4 hlen,fac;
  ub4 bit = 0;

  idhshcnt = 0;

  if (estcnt > hi20) {
    warning("estimated unique ID count %u`",estcnt);
    estcnt = min(estcnt,hi24);
    fac = 4;
  } else if (estcnt > hi16) fac = 8;
  else fac = 16;
  hlen = estcnt * fac;

  idhshlen = 1;
  while (idhshlen < hlen) { idhshlen <<= 1; bit++; }
  idhshmask = idhshlen-1;
  idhshbit = bit;

  hlen = idhshlen;
  idhsh = alloc(hlen,ub4,0,"lex id hash",nextcnt);
  info("%u entry id hash from u/id %u/%u",idhshlen,estcnt,cnt);
}

static ub4 id_nplen;

static ub4 idcheck(const ub1 *nam,ub2 len,ub4 v)
{
  ub4 x = idhsh[v];
  ub4 np,id;

  if (x == 0) { // slot free
    id = uidcnt++;
    if (id >= idtablen) ice(hi32,"id %u '%.*s' exceeds %u",id,len,nam,idtablen);
    idhsh[v] = id;
//    vrb("add '%s'",idnampool+idnampos);
    np = idnampos = align4(idnampos);
    if (np + len + 1 >= id_nplen) ice(hi32,"id nampool %u '%.*s' exceeds %u",np+len,len,nam,id_nplen);
    memcpy(idnampool+np,nam,len);
    idhshcnt++;
    if (len > idnmax) idnmax = len;
    idtab[id] = np;
    // info("add id %u nid %u",id,np);
    idnampos = np + len + 1;
    return id; // new
  } else {
    np = idtab[x];
    if (np + len + 1 >= id_nplen) ice(hi32,"id nampool %u '%.*s' exceeds %u",np+len,len,nam,id_nplen);
    if (idnampool[np+len] == 0 && samestr(idnampool+np,nam,len)) return x; // existing: common
    else {
      idhshmis++;
      return hi32;
    }
  }
}

// get or if none insert id. returns idnid.idid
static ub4 idgetadd(const ub1 *nam,ub2 len,ub4 hc)
{
  ub4 v,v0;
  ub4 x;
  ub4 hc2;

  // info("add id %.*s",len,nam);
  hc = (hc >> idhshbit) ^ hc;
  v = hc & idhshmask;

  x = idcheck(nam,len,v);
  if (x != hi32) return x;
  else { // probe once with second hash
    hc2 = hc >> idhshbit;
    v += hc2 & idhshmask;
    if (v >= idhshlen) v -= idhshlen;
    x = idcheck(nam,len,v);
    if (x != hi32) return x;
    else {
      v0 = v;
      do { // linear
        v = (v + 1) & idhshmask;
        x = idcheck(nam,len,v);
        if (x != hi32) return x;
      } while (v != v0);
      ice(0,"TODO resize id hash table overflow at %u of %u",idhshcnt,idhshlen);
    }
  }
}

static ub2 *id2tab;
static ub2 *id2nams;
static ub1 id2ch1map[256];
static ub1 id2ch1imp[256];
static ub1 id2ch2map[256];
static ub1 id2ch2imp[256];
static ub1 id2chr[256];
static ub1 id2nch1,id2nch2,id2shift1,id2shift2;
static ub2 id2mask1,id2mask2;

static ub2 id2getadd(ub2 n,ub1 c1,ub1 c2)
{
  ub1 a = id2ch1map[c1];
  ub1 b = id2ch2map[c2];
  ub2 id;
  ub2 ndx;

  if (a == 0xff || b == 0xff) ice(n,"pass %u invalid id2 '%s' '%s'",pass,chprint(c1),chprint(c2));
  ndx = (a << id2shift1) + b;
  id = id2tab[ndx];
  if (id != hi16) {
    return id;
  }
  id2tab[ndx] = uid2cnt;
  id2nams[uid2cnt] = ndx;
  return uid2cnt++;
}

static ub1 id1tab[256];
static ub1 id1inv[256];

static ub1 id1getadd(ub1 c)
{
  ub1 id = id1tab[c];

  if (id == 0xff) {
    id = uid1cnt++;
    id1tab[c] = id;
    id1inv[id] = c;
  }
  return id;
}

static void id2nam(ub2 id,ub1 *dst)
{
  ub2 ndx = id2nams[id];
  ub2 a,b;

  a = ndx >> id2shift1;
  b = ndx & id2mask1;

  dst[0] = id2ch1imp[a];
  dst[1] = id2ch2imp[b];
  dst[2] = 0;
}

static ub1 *idnnam(ub4 id)
{
  if (id >= idtablen) ice(0,"id %u above idtab %u",id,idtablen);
  ub4 nid = idtab[id];
  // info("id %u nid %u",id,nid);
  return idnampool + nid;
}

ub1 *idnam(ub4 id)
{
  ub4 nid;
  ub2 x2;
  static ub1 buf[4];

  if (id < uid1cnt) { *buf = id1inv[id]; buf[1] = 0; return buf; }
  else if (id < uid2cnt) { id2nam(id - uid1cnt,buf); return buf; }
  else return idnnam(id - uid1cnt - uid2cnt);
}

static void mkid2tab(void) {
  ub2 c;
  ub2 n1=0,n2=0;
  ub1 x;

  for (c = 0; c < 256; c++) {
    id2ch1map[c] = 0xff;
    id2ch2map[c] = 0xff;
    x = id2chr[c];
    if (x & 1) { id2ch1map[c] = n1; id2ch1imp[n1++] = c; }
    if (x & 2) { id2ch2map[c] = n2; id2ch2imp[n2++] = c; }
  }
  vrb("id2map %u,%u",n1,n2);
  if ( (n1 | n2) == 0) return;
  id2nch1 = nxpwr2(n1,&id2shift1);
  id2nch2 = nxpwr2(n2,&id2shift2);
  id2mask1 = id2nch1-1;
  id2mask2 = id2nch2-1;
  id2tab = (ub2 *)minalloc(id2nch1 * id2nch2 * 2,2,0xff,"lex id2tab");
  id2nams = (ub2 *)minalloc(id2nch1 * id2nch2 * 2,2,Mnofil,"lex id2nam");
}

static void mkslithash(ub4 cnt)
{
  ub4 hlen;
  ub4 bit = 0;

  if (cnt < 16) hlen = cnt+64;
  else if (cnt > hi20) {
    warning("string lit count %u`",cnt);
    cnt = hi20;
    hlen = cnt * 2;
  } else hlen = cnt * 4;

  slithshlen = 1;
  while (slithshlen < hlen) { slithshlen <<= 1; bit++; }
  slithshmask = slithshlen-1;
  slithshbit = bit;

  slithsh = alloc(slithshlen,ub4,0,"lex slit hash",nextcnt);
  info("%u entry slit hash",slithshlen);
}

static ub4 slitcheck(ub1 *pool,ub4 nam0,ub4 nam1,ub4 v,ub1 ctl)
{
  ub4 x,np,id;
  ub4 l1,len = nam1 - nam0;

  if (v >= slithshlen)
    ice(0,"slit ndx %u above %u for %.*s",v,slithshlen,len,pool+nam0);

  x = slithsh[v];

  if (x == 0) { // slot free - consolidate pool
    id = ++slitucnt;
    if (id >= slitidlen) ice(0,"slit id %u above %u",id,slitidlen);
    slithsh[v] = id;
    np = slitpos;
    slitpos = align4(nam1 + 1);
    if (slitpos >= slittop) ice(0,"slit pos %u above top %u",nam1,slittop);
    slithshcnt++;
    slitids[id] = np | ((ub8)len << 32);
    // vrb("add slit len %u pos %u '%s' id %u ctl %u",len,np,chprintn(pool+nam0,min(len,64)),id,ctl);
    return id; // new

  } else {
    if (x >= slitidlen) ice(0,"slit id %u/%u above %u for v %u '%.*s'.%u",x,slitucnt,slitidlen,v,len,pool+nam0,len);
    l1 = slitids[x] >> 32;
    np = slitids[x] & hi32;
    // info("v %u x %u nam0 %u top %u",v,x,nam0,slittop);
    if (l1 == len && memcmp(pool + np,pool + nam0,len) == 0) return x;
    else {
      slithshmis++;
      return 0;
    }
  }
}

// get or if none insert
static ub4 slitgetadd(ub1 *pool,ub4 nam1,ub1 ctl)
{
  ub4 nam0 = slitpos;
  ub4 len = nam1 - nam0;
  ub4 v;
  ub4 x,id;
  ub4 hc,hc2;
  ub2 lim;

  if (nam1 >= slittop) ice(0,"slit pos %u above top %u",nam1,slittop);
  pool[nam1] = 0;
  // info("add slit '%s'",pool + nam0);
  if (len >= Slitint) {
    slitpos = align4(nam1 + 1);
    if (slitpos >= slittop) ice(0,"slit pos %u above top %u",nam1,slittop);
    id = ++slitucnt;
    slitids[id] = nam0 | ((ub8)len << 32);
    return id;
  }
  // info("len %u %c",len,pool[nam0]);
  hc = hashalstr(pool+nam0,len,Hshseed);
  hc = (hc >> slithshbit) ^ hc;
  v = hc & slithshmask;

  x = slitcheck(pool,nam0,nam1,v,ctl);
  if (x) return x;
  else { // probe once with second hash
    hc2 = hc >> slithshbit;
    v = (v + hc2) & slithshmask;
    if (v >= slithshlen) v -= slithshlen;
    x = slitcheck(pool,nam0,nam1,v,ctl);
    if (x) return x;
    else {
      lim=4;
      do { // linear
        v = (v + 1) & slithshmask;
        x = slitcheck(pool,nam0,nam1,v,ctl);
        if (x) return x;
      } while (--lim);
      slitpos = align4(nam1 + 1); // skip dedup
      id = ++slitucnt;
      if (id >= slitidlen) ice(0,"slit id %u above %u",id,slitidlen);
      slitids[id] = nam0 | ((ub8)len << 32);
      info("add slit '%s' len %u id %u pos %u",pool+nam0,len,id,nam0);
      return id;
    }
  }
}

#if Kwcnt > 0
static inline enum token lookupkw(const ub1 *nam,ub1 len,ub4 hc)
{
  ub1 x,m;
  ub4 ndx;
  enum token kw;

  if (len > hikwlen) return t99_count;
  else if (len >= mikwlen) m = 0xf0;
  else m = 0xf;

  x = kwhshlut[hc & 0xff]
      | kwhshlut[(hc >> 8) & 0xff]
      | kwhshlut[(hc >> 16) & 0xff]
      | kwhshlut[hc >> 24];

  if ( (x & m) != m) return t99_count;

  ndx = (hc >> Kwhshbit) ^ hc;
  kw = kwhsh[ndx & Kwhshmask];
  if (kw == t99_count) return t99_count;

  if (tkwnamlens[kw] == len && samestr(nam,tkwnampool + tkwnamposs[kw],len)) return kw;
  else return t99_count;
}
#endif

#ifdef Bltcnt
static inline enum Bltin lookupblt(const ub1 *nam,ub2 len,ub4 hc)
{
  ub1 ndx,x,m;
  enum Bltin bt;

  if (len > hibltlen) return B99_count;

  ndx = (hc >> Blthshbit) ^ hc;

  bt = blthsh[ndx & Blthshmask];
  if (bt == B99_count) return B99_count;

  if (len >= mibltlen) m = 0xf0;
  else m = 0xf;

  x = blthshlut[hc & 0xff]
      | blthshlut[(hc >> 8) & 0xff]
      | blthshlut[(hc >> 16) & 0xff]
      | blthshlut[hc >> 24];

  if ( (x & m) != m) return B99_count;

  if (bltnamlens[bt] == len && samestr(nam,bltnampool + bltnamposs[bt],len)) return bt;
  else return B99_count;
}
#else
  #define lookupblt(nam,len,hc) B99_count
#endif

#ifdef Duncnt
static inline enum Dunder lookupdun(const ub1 *nam,ub2 len)
{
  ub4 hc;
  ub1 ndx,x,m;
  enum Dunder dun;
  ub1 albuf[Idlen];
  const ub1 *idp;

  if (len > hidunlen) return D99_count;

  if ( (ub8)nam & 3) {
    memcpy(albuf,nam,len);
    idp = albuf;
  } else idp = nam;

  ub4 seed,mask;
  ub2 bit,shift;
  const enum Dunder *hsh;

  if (*nam & 1) {
    seed = Hshd1seed;
    bit = Dun1hshbit;
    shift = Hshd1shift;
    mask = Dun1hshmask;
    hsh = dun1hsh;
  } else {
    seed = Hshd0seed;
    bit = Dun0hshbit;
    shift = Hshd0shift;
    mask = Dun0hshmask;
    hsh = dun0hsh;
  }
  // info("dun '%.*s'.%u",len,idp,len);
  hc = hashalstr(idp,len,seed);
  hc = (hc >> bit) ^ hc;
  ndx = (hc >> shift) & mask;
  dun = hsh[ndx];
  // info("tbl %u ndx %x dun %u",*nam & 1,ndx,dun);
  if (dun == D99_count) return D99_count;

  if (dunnamlens[dun] == len && samestr(idp,dunnampool + dunnamposs[dun],len)) return dun;
  else return D99_count;
}
#else
  #define lookupdun(len,hc) D99_count
#endif

static ub4 idsketch;
#define R(x) ~(x) & ((x)+1)

// cs.princeton.edu/~rs/talks/AC11-Cardinality.pdf  philippe flajolet / martin '85
static void exp_first0(ub4 x,ub4 *sketchs)
{
  ub4 i,s = ((x >> 16) ^ x) * 0x45d9f3b; // int32 hash after thomas muller

  s = ((s >> 16) ^ s) * 0x45d9f3b;
  s = (s >> 16) ^ s;
  i = s & 0xf;

  ub4 e = R(x);

  sketchs[i] |= e;
  idsketch |= e;
}

static ub4 exp_est(ub4 *sketchs)
{
  ub4 x,sum=0,i;

  for (i=0; i < 16; i++) {
    x = R(sketchs[i]);
    vrbo("%2u %08x",i,x);
    sum += x;
  }
//  sum >>= 4;
  x = R(idsketch);
  info("  %x vs %x",sum,x);

  return sum + (sum >> 1);
}

static int tryopen(cchar *dir,cchar *name,bool need)
{
  char path[Pathname];
  cchar *p;
  int fd;

  if (dir == nil || *dir == 0 || (dir[0] == '.' && dir[1] == '/') ) p = name;
  else {
    mysnprintf(path,0,Pathname,"%s/%s",dir,name);
    p = path;
  }

  if (osopenseq(p,&fd) && need) oserror("cannot open %s",p);
  return fd;
}

static ub1 lxatox1(ub1 c)
{
  ub1 x;

  if (c >= '0' && c <= '9') x = c - '0';
  else if (c >= 'A') x = (c | 0x20) - 'a' + 10;
  else return 0xff;
  return x;
}

static ub4 doescx(const ub1 * restrict src,ub4 sn,ub1 *pool,ub4 *plitx,bool isbin)
{
  ub4 litx = *plitx;
  ub1 x,x1,x2,c = src[sn],d = src[sn+1];

  x1 = lxatox1(c);
  x2 = lxatox1(d);

  if ( (x1 | x2) > 0xf) { swarn(0,"illegal hex escape seq '%s%s'",chprint(c),chprint(d)); return sn; }

  x = x1 << 4 | x2;

  if (x < 0x80 || isbin) pool[litx++] = x;
  else { // utf8
    pool[litx]   = 0xc0 | (x >> 6);
    pool[litx+1] = 0x80 | (x & 0x3f);
    litx += 2;
  }
  *plitx = litx;
  return sn+2;
}

static ub4 doescu(const ub1 * restrict src,ub4 sn,ub1 *pool,ub4 *plitx,ub1 ctl)
{
  ub4 litx = *plitx;

  pool[litx] = *src;
  switch(ctl) {
  case 'U': serror(sn,"\\Uxx.. in  string lits at pos %u TODO",litx);
  case 'u': serror(sn,"\\uxx.. in  string lits at pos %u TODO",litx);
  }
  return sn+1;
}

static ub4 doescn(const ub1 * restrict src,ub4 sn,ub1 *pool,ub4 *plitx)
{
  ub4 litx = *plitx;
  ub4 s0 = sn,len;
  ub1 c;

  do {
    c = src[sn++];
  } while ( (c >= 'A' && c <= 'Z') || c == ' ' || c == '-');
  len = sn - s0;
  memcpy(pool + litx,src + s0,len);
  litx += len;
  if (c == '}') { // named unicode todo
  }
  *plitx = litx;
  return sn;
}

#define Dent 256

#define B32max (1U << 30)
#define X32max 0xfffffff
#define D32max (1U << 28)
#define E16max 0xff

static ub4 tkstats[T99_count];

static void doemit(struct lexsyn *lsp,ub4 *lntab,cchar *name,bool emit,bool pretty,bool log)
{
  const enum Token *tks = lsp->toks;
  const ub2 *atrs = lsp->atrs;
  const ub8 *bits = lsp->bits;
  const ub4 *fpos = lsp->fpos;
  const ub4 *cmts = lsp->cmts;
  const cchar *src = lsp->src;

  ub4 tkcnt = lsp->tkcnt;
  ub4 tbcnt = lsp->tbcnt;
  ub4 cmcnt = lsp->cmtcnt;
  const ub1 *slitpool = lsp->slitpool;

  enum Token tk=0;
  ub2 atr,at;
  ub4 dn,bn=0,ncmt=0,dnn=0;
  ub8 x8=0;
  ub4 x4,np,cmt0,i;
  ub4 lno = 0,plno = 0,clno = 0;
  ub4 col;
  ub2 dent=0;
  ub4 bitatr;
  ub2 x2;
  ub4 id;
  ub4 fps,xat;
  ub4 pos;
  ub4 slen=0,clen,len,nlen,blen = 4090;
  ub4 n2,n3;
  char buf[4096];
  char buf2[Idlen+64];
  char sbuf[8];
  char c,d,e,sign=' ',Q=0;
  ub2 nQ=0;
  cchar *tval;
  cchar *tnam;
  cchar *sp=nil;
  cchar *p;
  bool isprv;
  struct bufile fp;
  char ppnam[1024];

  if (pretty) {
    sp = strrchr(name,'.');
    if (sp) len = sp - name;
    else { len = strlen4(name); sp = ".py"; }
    mysnprintf(ppnam,0,1024,"%.*s.pretty%s",len,name,sp);
    fp.nam = ppnam;
    fp.dobck = 1;

    myfopen(FLN,&fp,16384,1);
    info("writing %s",ppnam);
    msgfls();
  }

  if (emit && name) msglog(name,"tks","lex");

  for (dn = 1; dn < tkcnt; dn++) {
    tk = tks[dn];
    atr = atrs[dn];
    fps = fpos[dn];
    xat = fps >> Lxabit; fps &= Lxamsk;

    while (fps >= lntab[lno]) lno++;
    while (lno && lntab[lno] > fps) lno--;

    if (lno) { col = fps - lntab[lno]; }
    else col = fps;

    c = d = ' '; tval = ""; pos = 0; isprv = 0;
    if (tk >= T99_count) ice(fps,"pos %u/%u - invalid token %u",dn,tkcnt,tk);
    tnam = tknam(tk);
    // sinfo(fps,"tk %u '%s' bn %u dn %u",tk,tnam,bn,dn);
    nlen = len = strlen(tnam);
    if (tk > T0grp) tval = tnam;

    if (bn > tbcnt) ice(0,"value pos %u above %u",bn,tbcnt);
    x8 = bits[bn];
    // info("bn %u bits %lx",bn,x8);
    bitatr = x8 >> 32;
    x4 = x8;

#ifdef Emitdetail
    at = atr & ~La_msk; atr &= La_msk;
    switch (tk) {
    case Tid:
      len = Idlen; x4 = hi32; c = ' '; tval = buf2;
      if (at & La_idprv) { isprv = 1; at &= ~La_idprv; }
      switch(at) {
      case 0:      d = '0'; x4 = atr; tval = idnnam(x4); // id4s
      break;

      case La_id1: d = '1'; c = id1inv[atr]; if (pretty) { buf2[0] = c; len=1; } break;
      case La_id2: d = '2'; id2nam(atr,buf2); len = 2; break;
      case La_id4: d = '4'; x4 = x8;
        // vrbo("ln %u id4 bn %u id %u",bitln,bn,x4);
        if (bitatr != dn) ice(fps,"id tk %u vs bit %u %lx at %u %s",dn,bitatr,x8, bn,cursrc);
        tval = idnnam(x4);
        // sinfo(fps," id id tk %3u bit %3u %2u %8s %c %c %s%.*s`z",dn,bn,tk,tnam,c,d,isprv ? "__" : "",len,tval);
        bn++;
      break;

      case La_idblt: d = 'b'; tval = bltnam(atr,&len); break;

      case La_iddun: d = 'd'; tval = buf; len = mysnprintf(buf,0,Idlen+4,"__%s__",dunnam(atr)); break;

      case La_id_: d = '_'; c = '_'; buf2[0] = '_'; len = 1; break;
      default: ice(fps,"unhandled atr %x id tk %u bit %u %s",at,dn,bn,cursrc);
      }
      // sinfo(fps," id id tk %3u bit %3u %2u %8s %c %c %s%.*s`z",dn,bn,tk,tnam,c,d,isprv ? "__" : "",len,tval);
    break;

    case Tnlit:
      tval = buf; sign = ' '; c = 'i'; d = 'b';
      switch (at) {
      case La_flit8n: sign = '-'; Fallthrough
      case La_flit8:
        c = 'f';
        // info("flit8 bn %u",bn);
        len = mysnprintf(buf,0,blen,"%u.0",(ub4)x8 & hi16);
        bn++;
        break;
      case La_flita: c = 'f'; Fallthrough
      case La_ilita: d = 'a';
        len = mysnprintf(buf,0,blen,"%.*s",atr,src + x4);
        bn++;
        break;
      case La_ilit4:
      case La_ilit4n:
        if (bitatr != dn) ice(fps,"ilit tk %u vs bit %u at %u %s",dn,bitatr,bn,cursrc);
        x4 = x8;
        bn++;
        len = mysnprintf(buf,0,blen,"%u",x4);
        // vrbo("ln %u nlit bn %u %u",bitln,bn,x4);
        break;

      default:
        x4 = atr;
        len = mysnprintf(buf,0,blen,"%u",x4);
      }
    break;

    case Tflit: d = 'F'; Fallthrough
    case Tslit: tval = buf;
      if (xat & 32) buf[pos++] = 'f';
      nQ = (xat & 16) ? 3 : 1;
      Q = (xat & 8) ? '"' : '\'';
      if (xat & 4) buf[pos++] = 'b';
      if (xat & 2) buf[pos++] = 'f';
      if (xat & 1) buf[pos++] = 'r';
      // info("slit at %x",at);
      switch (at) {
      case 0:        slen = 1; e = atr; sp = (cchar *)&e; break; // slit 1
      case La_slit0: slen = 0; sp = ""; break;
      case La_slit2: slen = 2; x8 = bits[bn]; sp = (cchar *)&x8;
//        if (bitatr != dn) ice(fps,"slit tk %u vs bit %u at %u %s",dn,bitatr,bn,cursrc);
        /* vrbo("ln %u slit2 bn %u '%.2s'",bitln,bn,sp); */ bn++; break;
      case La_slit3: slen = 3; x8 = bits[bn]; sp = (cchar *)&x8;
//        if (bitatr != dn) ice(fps,"slit tk %u vs bit %u at %u %s",dn,bitatr,bn,cursrc);
       /* vrbo("ln %u slit4 bn %u '%.3s'",bitln,bn,sp); */ bn++; break;
      case La_slits:
      case La_slit:
        if (at == La_slits) id = atr;
        else {
          if (bitatr != dn) ice(fps,"slit tk %u vs bit %u at %u %s",dn,bitatr,bn,cursrc);
          id = x8; bn++;
          // vrbo("ln %u id bn %u",bitln,bn);
        }
        slen = 5;
        if (id >= slitidlen) { swarn(fps,"slit id %u above %u ln %u %s",id,slitidlen,bitatr,cursrc); sp = "*ICE*"; }
        else {
          x8 = slitids[id];
          slen = x8 >> 32;
          x4 = x8 & hi32;
          if (x4 >= slittop) { swarn(fps,"pos %u",x4); sp = "*ICE*"; }
          else sp = slitpool + x4;
        }
        break;
      default: sp = "*inv*"; slen = 5;
      }
      if (slen > 4 && sp[0] == '.' && sp[1] == '/') { vrbo("%.*s",slen,sp); slen = min(slen,sizeof(cursrc)-1); memcpy(cursrc,sp,slen); cursrc[slen] = 0; }
    break;

    case Top:
      tnam = "op";
      c = atr & 0xff; tval = buf2;
      buf2[0] = c; len = 1;
      if (atr & Lxop2) buf2[len++] = c;
      if (atr & Lxoe) buf2[len++] = '=';
      // sinfo(fps," op '%.*s' ",len,tval);
    break;

    case Taas:
      c = atr & 0xff; tval = buf2;
      buf2[0] = c; len = 1;
      if (atr & Lxop2) buf2[len++] = c;
      buf2[len++] = '=';
    break;

    case Tind: len=0; dent += 2; break;
    case Tded: len=0; dent -= min(dent,2); break;

    case Tsepa: if (atr == 0) { tval = buf2; buf2[0] = '\n'; len = 1; plno++; } break; // at eol

    default: break;
    }
#endif

    if (pretty) {
      while (ncmt + 1 < cmcnt && cmts[ncmt] < fps) { // comment

        cmt0 = cmts[ncmt++];
        clen = cmts[ncmt++] - cmt0;

        while (cmt0 >= lntab[clno]) clno++;
        while (clno && lntab[clno] > cmt0) clno--;

        while (plno < clno) { myfputc(&fp,'\n'); plno++; }

        if (clen) myfwrite(&fp,src + cmt0,clen);
        plno++;
        // info("cmt %u fps %u-%u len %u '%s'",ncmt,cmt0,cmts[ncmt-1],slen,chprintn(src + cmt0,min(clen,64)));
      }
      if (plno < lno && *tval != '\n') {
        while (plno < lno) { myfputc(&fp,'\n'); plno++; }
        if (dent) myfprintf(&fp,"%*s",dent,"");
      }
      if (lang_mocklex == 0 && isprv) myfputs(&fp,"__");
      if (tk < T99_kwd) {
        if (lang_mocklex) myfprintf(&fp,"Def abc_%u ( abc = 123, def ) ; ",dn & 0xfff);
        else {
          if (tk >= T99_mrg) { tnam = tkwnampool + tkwnamposs[atr]; nlen = tkwnamlens[atr]; }
          myfwrite(&fp,tnam,nlen);
        }
      } else if (tk == Tid) {
        if (len == Idlen) len = strlen(tval);
        myfwrite(&fp,tval,len);
      } else if (tk == Tnlit) {
//        info("ln %u c %c len %u %.*s",lno,*tval,len,len,tval);
        while (len && (*tval == '-' || *tval == '+')) { tval++; len--; }
        myfwrite(&fp,tval,len);
      } else if (tk == Tslit || tk == Tflit) {
        if (lang_mocklex) myfputs(&fp," { ");
        for (i = 0; i < nQ; i++) buf[pos++] = Q;
        myfwrite(&fp,buf,pos); pos = 0; i = 0; // prefix + open q
        while (i < slen) {
          n2 = min(slen-i,1024);
          p = chprintn(sp + i,n2,&n3,xat);
          i += n2;
          myfwrite(&fp,p,n3);
        }
        for (i = 0; i < nQ; i++) buf[pos++] = Q;
        myfwrite(&fp,buf,pos);
        if (lang_mocklex) { myfputs(&fp," } ; "); dnn += 4; }
      } else if (lang_mocklex == 0 && len == 1) myfputc(&fp,*tval);
      else if (len) {
        if (lang_mocklex) {
          switch (tk) {
          case Tid:   myfprintf(&fp," ( %s%.*s ) ; ",isprv ? "__" : "",len,tval); dnn += 4; break;
          case Tnlit: myfprintf(&fp," [ %.*s ] ; ",len,tval); dnn += 4; break;
          case Top:
          case Tdas:
          case Taas: myfprintf(&fp," lhs_%x %.*s rhs_%x ; ",dn & 0xfff,len,tval,dn & 0xfff); dnn += 4; break;
          case Tsepa: myfputc(&fp,';'); dnn++; break;
          default: break;
          }
        } else myfwrite(&fp,tval,len);
      }
      myfputc(&fp,' ');
    } // pretty

    if (emit | log) {
#ifdef Emitdetail
      switch (tk) {
      case Tnlit:
        info("%s.%3u.%-2u: %3u %2u %8s %c %c %c%.*s",name,lno,col,dn,tk,tnam,c,d,sign,len,tval);
        break;
      case Tslit: case Tflit:
        p = chprintn(sp,min(slen,64),nil,xat & ~16);
        info("%s.%3u.%-2u: %3u %2u %8s %c %c len %u %c%s%c",name,lno,col,dn,tk,tnam,c,d,slen,Q,p,Q);
        if (slen > 64) {
          p = chprintn(sp + slen - 64,64,nil,xat & ~16);
          info("%s.%3u.%-2u: %3u %2u %8s ... '%s'",name,lno,col,dn,tk,tnam,p);
        }
        break;
      case Tco: case Tcc: case Tro: case Trc:
        info("%s.%3u.%-2u: %3u %2u %8s %c %c %s lvl %u",name,lno,col,dn,tk,tnam,c,d,tnam,atr);
        break;
      default: info("%s.%3u.%-2u: %3u %2u %8s %c %c %.*s",name,lno,col,dn,tk,tnam,c,d,len,tval);
      }
#else
      info("%3u %-8s %u",dn,tnam,tk);
#endif
    }
  }
  sinfofln(FLN,lsp->srclen,"EOF");

  if (pretty) {
    myfputc(&fp,'\n');
    myfclose(&fp);
    info("wrote %s",ppnam);
    showcnt("ptoken",dnn);
    msgfls();
  }

  if (emit) msglog(nil,nil,"lex");
}

enum Tkpart { Tp_bit,Tp_fps,Tp_tk,Tp_atr,Tp_cmt,Tp_cnt };

static int lex(struct fnaminf *mf,const unsigned char * restrict sp,ub4 slen,struct lexsyn *lsp,ub8 T0)
{
  int rv = 0;
  ub4 len;
  ub2 len2;

  // tokens
  enum Token tk=0;
  enum Bltin blt;
  enum Dunder dun;

  ub4 tkcnt=0;
  void *tkbas=nil;
  ub1 *tks=nil;      // token
  ub2 atr,*atrs=nil; // token atr
  ub8 *bits=nil;     // token value bit
  ub4 fps,xat=0,*fpos=nil; // file coord
  ub4 cmt0,ncmt=0,*cmts=nil; // comment

  struct mempart tkpart[5];

  ub4 tkgrps[Tkgrp];
  ub1 grp;

  // str lits
  ub1 *slitpool=nil;
  ub4 slitx=0,slitpx=0;
  ub4 slitppos=0;
  ub4 idxpos=0;
  ub1 slitctl=0,orgslitctl=0;

  // ids
  ub1 albuf[Idlen];
  const ub1 *idp;
  ub4 idsketchs[16];
  ub4 idcnt=0,id1cnt=0,id2cnt=0,euidcnt=0;

  // kwd, bltin, dunder
  ub4 kwcnt=0;
  ub4 bltcnt=0;
  ub4 duncnt=0;

  // str lits
  ub4 slitcnt=0,slitcatcnt=0;

  // int lits
  ub4 ilitcnt=0,ilit1cnt=0;
  ub4 ilitacnt=0,flitacnt=0;
  ub4 u4v=0;

  bool litbin = 1;
  bool litfpi=0;
  ub1 ilitctl = 0;

  // flt lits
  ub4 flitcnt=0;
  ub4 fdp=0; // dot pos
  ub2 fxp=0; // e+nn
  bool fxs=0; // exp sign

  // indent
  ub2 dentst[Dent];
  ub2 dent;
  ub2 dentlvl=0;

  // braces
  ub4 bolvls[Depth];
  ub1 bolvlc[Depth];
  ub2 bolvl=0,fsxplvl=hi16;
  ub2 colvl=0,solvl=0,rolvl=0;
  ub2 rocnt=0,rccnt=0,cocnt=0,cccnt=0,socnt=0,sccnt=0;

// line/col/dent
  ub4 l=0;
  ub4 nlcol=0;
  ub4 *lntab=nil;
  ub4 lncnt=0;
  bool hasdent;

  ub4 i,cnt,cnt1;

  ub8 T1=T0;

  timeit(&T1,nil);

  ub1 c,prvc1,prvc2,signc;
  ub4 dn,bn = 0,orgbn=0,dn1=0;
  ub4 n = 0;

  ub4 idnplen=0;

  dentlvl=0;
  memset(dentst,0,sizeof(dentst));

  memset(idsketchs,0,16 * 4);

  memset(id2chr,0,256);
  memset(albuf,0,Idlen);

  ub1 t=0,u;

  ub1 Q = 0,orgQ = 0;
  ub4 N = 0;
  ub1 R0 = 0,R1 = 0,R2 = 0,R3 = 0,orgR0=0;
  ub1 sign = 0;

  ub4 id=0;
  ub1 x1,x11;
  ub4 x4;
  ub8 x8;

  ub4 hc=0;

  enum Token kwd;
  enum token kw;
  ub4 idhilen = 0;

  memset(tkgrps,0,sizeof(tkgrps));
  memset(bolvlc,0,Depth);

  pass = 1;
  dn = 1;
  if (slen > 3 && sp[0] == '#' && sp[1] == '!') { // skip shebang
    while (n < slen && sp[n] != '\n') n++;
    if (n + 1 >= slen) {
      info("%s is an empty shebang",lsp->name);
      return 0;
    }
    sp += n; n = 0;
  }

  infofln(FLN,"+lex1");

#undef  FLN
#define FLN __LINE__|(Shsrc_lex1<<16)

#include "lextb1.i"

#undef  FLN
#define FLN __LINE__|(msgfile<<16)

  infofln(FLN,"-lex1");

  ub4 tkx1cnt = tkcnt = dn;
  showcnt("xtoken",tkcnt);
  showcnt("line",l);
  lncnt = l;

  if (verbose) timeit2(&T1,slen,"pass 1 tokenised ` in");

  showcnt("3int 1 lit",ilit1cnt);
  showcnt("3int n lit",ilitcnt);
  showcnt("3flt n lit",flitcnt);

  showcnt("3len n slit",slitncnt);
  showcnt("3len 0 slit",slit0cnt);
  showcnt("3len 1 slit",slit1cnt);
  showcnt("3len 2 slit",slit2cnt);
  showcnt("3len 3 slit",slit3cnt);
  showcnt("3len x slit",slitxcnt);

  if (n != slen + 1) warning("len %u vs %u",n,slen);

  if (slitncnt) mkslithash(slitncnt);

  slitcnt = slitncnt + slit2cnt + slit3cnt + slitxcnt;

  ub4 bitcnt = ilitcnt + flitcnt + slitcnt;

  if (slitcnt) {
    slitpos += 5 * (slitcnt+2); // align + 0-term
    showsiz("slit pool",slitpos);
    slitidlen = slitcnt * 2 + 64;
    slitids = alloc(slitidlen,ub8,Mnofil,"lex slit ids",nextcnt);
  }

  slitcnt += slit0cnt + slit1cnt;
  showcnt("3slit",slitcnt);

  if (idcnt) {
    showcnt("3ident / kwd",idcnt);
    while (idhilen < Idlen && albuf[idhilen]) idhilen++; // todo
    if (idnplen >= Idpool) ice(n,"ID literal pool exceeds max %u`B",Idpool);
    idnplen += 5 * (idcnt+1); // align + 0-term
    id_nplen = idnplen;
    info("idpool %u`B max len %u",idnplen,idhilen);
  }

  if (tkcnt >= Tokencnt) serror(n,"token count %u exceeds limit %u",tkcnt,Tokencnt);

  bitcnt += idcnt;

  showcnt("3value",bitcnt);

  ub4 xcnt = slit0cnt + slit1cnt + id1cnt + ilit1cnt;

  tkgrps[0] += bitcnt + xcnt + id2cnt;

  tkcnt += slit0cnt + slit1cnt + slit2cnt + slit3cnt + slitncnt + slitxcnt;
  tkcnt += ilit1cnt + ilitcnt + flitcnt;
  tkcnt += id1cnt + id2cnt + idcnt;

  if (tkcnt == 1) {
    info("%s is empty",lsp->name);
    return 0;
  }

  showcnt("3ident2",id2cnt);
  showcnt("3ident1",id1cnt);

  showcnt("3token",tkcnt);
  showcnt("3total 1",dn1);

  if (tkcnt >= Tokencnt) serror(n,"token count %u exceeds limit %u",tkcnt,Tokencnt);
  info("dif %u",4468343 - tkcnt);

  lsp->idcnt = idcnt + id1cnt + id2cnt;

  if (idcnt > 1024) {
    euidcnt = exp_est(idsketchs);
    showcnt("3est unique ident",euidcnt);
  }

  showcnt("colvl",colvl);
  showcnt("solvl",solvl);
  showcnt("rolvl",rolvl);

  showcnt("rocnt",rocnt);
  showcnt("rccnt",rccnt);
  showcnt("cocnt",cocnt);
  showcnt("cccnt",cccnt);

  showcnt("cmt",ncmt);

  if (globs.rununtil == 2) { infofln(FLN,"until lex pass 1"); return 0; }

  for (i = 0; i < Tp_cnt; i++) tkpart[i].fil = Mnofil;
  tkpart[Tp_fps].nel = tkpart[Tp_tk].nel = tkpart[Tp_atr].nel = tkcnt+Tkpad;
  tkpart[Tp_cmt].nel = ncmt;

  tkpart[Tp_fps].siz = 4;
  tkpart[Tp_tk].siz = 1;
  tkpart[Tp_atr].siz = 2;
  tkpart[Tp_cmt].siz = 4;

  tkpart[Tp_bit].siz = 8;
  tkpart[Tp_bit].nel = bitcnt;

  tkbas = allocset(tkpart,Tp_cnt,Mnofil,"lex tokens",nextcnt);
  bits = tkpart[0].ptr;
  fpos = tkpart[Tp_fps].ptr;
  tks  = tkpart[Tp_tk].ptr;
  atrs = tkpart[Tp_atr].ptr;
  cmts = tkpart[Tp_cmt].ptr;

  slittop = slitpos;
  if (slitpos) {
    slittop += 2;
    slitpool = alloc(slittop,ub1,Mnofil,"lex slit pool",nextcnt);
  }

  if (idcnt) {
    idnampool = alloc(idnplen,ub1,0,"lex idnpool",nextcnt);
    idnampos = 4;
    if (euidcnt == 0) { idtablen = idcnt; euidcnt = idcnt; }
    else idtablen = nxpwr2(euidcnt * 2 + 1024,nil);
    mkidhash(euidcnt,idcnt);
    idtab = alloc(idtablen,ub4,Mnofil,"lex id tab",nextcnt);
  }
  if (id2cnt) {
    mkid2tab();
  }
  memset(id1tab,0xff,256);

  slitpos = 4;

  ub4 lntabsiz = (lncnt + 2) * 4;
  lntab = lncnt < 1024 ? minalloc(lntabsiz,4,Mnofil,"lex lntab") : medalloc(lntabsiz,4,"lex lntab");
  memset(lntab,0xff,lntabsiz);

  setsrcmfile(mf,lntab,lncnt,n);

  n = 0;
  dn = 1;
  bn = 0;
  l = 0;
  ncmt = 0;

  fxp = 0;
  fdp = 0;

  slitctl = orgslitctl = 0;
  fsxplvl = hi16;
  R0 = R2 = R3 = 0;

  dentlvl=0;
  dentst[0] = 0;

  idcnt = id1cnt = id2cnt = 0;

  pass = 2;

  infofln(FLN,"+lex2");

#undef  FLN
#define FLN __LINE__|(Shsrc_lex2<<16)

#include "lextb2.i"

#undef  FLN
#define FLN __LINE__|(msgfile<<16)

  infofln(FLN,"-lex2");

  if (verbose) timeit2(&T1,slen,"pass 2 tokenised `B in");

  showcnt("3token",dn);
  showcnt("3line",l);

  if (n != slen + 1) warning("len %u vs %u",n,slen);

  showcnt("bltin",bltcnt);
  showcnt("dunder",duncnt);

  if (idhshcnt != uidcnt) ice(0,"idhshcnt %u vs %u",idhshcnt,uidcnt);

  if (idhshcnt) {
    info("%3u` uniq idents, est %u` max len %u",idhshcnt,euidcnt,idnmax);
    info("id hash table used %u` of %u` retry %u`",idhshcnt,idhshlen,idhshmis);
  }
  showcnt("3 ident1",id1cnt);
  showcnt("3uident1",uid1cnt);

  showcnt("3 ident2",id2cnt);
  showcnt("3uident2",uid2cnt);

  if (slithshcnt) {
    showcnt("3hash slit",slithshcnt);
    showcnt("3uniq slit",slitucnt);
    info("slit hash table used %u` of %u` retry %u` skipped %u`",slithshcnt,slithshlen,slithshmis,slitlimcnt);
  }
  showcnt("3slit concat",slitcatcnt);

  bits[bn] = 0;
  showcnt("3value",bn);

  if (tkcnt < slitcatcnt) {
    error("%u slit concat vs %u :1 tokens",slitcatcnt,tkcnt);
    return 1;
  }
  tkcnt -= slitcatcnt;

  if (dn > tkcnt) {
    error("%u :1 vs %u :2 tokens dif %u",tkcnt,dn,dn - tkcnt);
    rv = 1;
  } else if (dn < tkcnt) {
    warning("%u :1 vs %u :2 tokens dif %u",tkcnt,dn,tkcnt - dn);
    rv = 0;
  }

  tkcnt = dn;

  if (l > lncnt) {
    error("%u :1 vs %u :2 lines",lncnt,l);
    rv = 1;
  } else if (l < lncnt) {
    warning("%u :1 vs %u :2 lines",lncnt,l);
  }
  lntab[l] = n;
  lntab[l+1] = n+1;

  memset(tks+tkcnt,T99_eof,Tkpad);

#if 1
  kwcnt = 0;
  for (dn = 1; dn < tkcnt; dn++) {
    tk = tks[dn];
    tkstats[tk]++;
  }
  cnt1 = 0;
  for (tk = 0; tk < T99_count; tk++) {
    cnt  = tkstats[tk];
    if (cnt) {
      cnt1 += cnt;
#if Kwcnt > 0
      if (tk < T99_kwd) kwcnt += cnt;
#endif
    }
  }
  showcnt("4total",cnt1);
  showcnt("4kwd",kwcnt);

  for (tk = 0; tk < T99_count; tk++) {
    cnt  = tkstats[tk];
    if (cnt) {
#if Kwcnt > 0
      if (tk < T99_kwd) kwcnt += cnt;
#endif
      info("%5u %s",cnt,tknam(tk));
    }
  }
#endif

  for (grp = 0; grp < Tkgrp; grp++) {
    cnt = tkgrps[grp];
    if (cnt) info("grp %u %u",grp,cnt);
    if (grp < Tkgrps) lsp->tkgrps[grp] = cnt;
  }

  lsp->nlitcnt = ilitcnt + flitcnt + ilit1cnt;

  lsp->src = sp;

  showcnt("token",dn);

  lsp->tkcnt = dn;
  lsp->tbcnt = bn;

  lsp->toks = tks;
  lsp->bits = bits;
  lsp->atrs = atrs;
  lsp->fpos = fpos;

  lsp->uidcnt = uidcnt;
  lsp->uid1cnt = uid1cnt;
  lsp->uid2cnt = uid2cnt;

  lsp->idnampool = idnampool;

  lsp->slitpool = slitpool;
  lsp->slitcnt = slitcnt;
  lsp->slittop = slittop;

  lsp->cmts = cmts;
  lsp->cmtcnt = ncmt;

  lsp->tkbas = tkbas;

  memcpy(lsp->tkgrps,tkgrps,sizeof(tkgrps));

  bool emit = globs.emit & 1;
  bool dolog = globs.log & 1;
  bool pretty = globs.emit >> 15;

  if (emit | pretty | dolog) doemit(lsp,lntab,mf->name,emit,pretty,dolog);

  if (bolvl) {
    sinfo(bolvls[0],"opening '%c' at lvl %u here",bolvlc[0],bolvl);
    serror(slen,"no matching '%c'",bolvlc[0]);
  }

  ub2 hidepth = (ub2)((ub1 *)memchr(bolvlc,0,Depth) - bolvlc);
  info("max depth %u",hidepth);
  lsp->hidepth = hidepth;

  if (idhsh) afree(idhsh,"lex id hash",nextcnt);

  if (globs.rununtil == 3) { infofln(FLN,"until lex"); return 0; }

  return rv;
}

int lexfile(ub4 fln,cchar *path,cchar *parpath,enum Inctype inc,struct lexsyn *lsp,ub8 T0)
{
  int rv;
  ub2 n = 0, dirsep = 0;
  char *ipath,*p;
  int fd = -1;
  struct fnaminf *fb;
  ub2 incdir=0;
  ub4 slen,xlen;
  ub4 nr;

  struct osstat ino;
  char chkpath[Pathname];

  ub8 T1=0;

  if (path == nil) { errorfln(FLN,fln,"nil file name for lex"); return 1; }
  else if (*path == 0) { errorfln(FLN,fln,"empty file name for lex"); return 1; }

  while (path[n]) { if (path[n] == '/') dirsep = n; n++; }
  if (n == dirsep + 1) { errorfln(FLN,fln,"lex: path '%s' is a directory",path); return 1; }

  timeit(&T1,nil);

  if (inc == Inone) {
    fd = tryopen(nil,path,1);
    if (fd == -1) return 1;
  } else if (inc == Iuser) { // search in dir of includer

    mysnprintf(chkpath,0,Pathname-2,"%.*s/%s",dirsep,parpath,path);
    fd = tryopen(nil,path,1);
    if (fd == -1) return 1;
  } else {

    while (fd == -1 && incdir < lsp->incdircnt) { // search in system dirs and -I
      mysnprintf(chkpath,0,Pathname-2,"%s/%s",lsp->incdirs[incdir],path);
      fd = tryopen(nil,chkpath,0);
      incdir++;
    }
    if (fd == -1) { errorfln(FLN,0,"cannot open %s",path); return hi32; }
  }

  if (osfdinfo(&ino,fd)) { osclose(fd); errorfln(FLN,0,"cannot get info for %s",path); return 1; }
//  if (ino.len >= (1U << 31)) { osclose(fd); errorfln(FLN,0,"%s length %lu exceeds %u",path,ino.len,1U << 31); return 1; }

  fb = getsrcmfile();

  fb->ino = ino.ino;
  fb->dev = ino.dev;

  if (chksrcmfile(fb)) {
    info("skip duplicate %s ",path);
    osclose(fd);
    return 0;
  }

  srcnam = path;

  slen = (ub4)ino.len;
  xlen = slen + max(Cclen+2,8); // pad with 0

  ub1 *sp;

  if (slen == 0) { info("%s is empty",path); osclose(fd); return 0; }
  sp = alloc(xlen,char,Mnofil,"lex file",nextcnt);

  timeit(&T1,nil);

  rv = osread(fd,sp,slen,&nr);
  if (rv) {
    if (rv < 0) oserror("cannot read %s",path);
    else error("cannot read %s",path);
    osclose(fd);
    return 1;
  }
  osclose(fd);
  if (nr != slen) { error("partial read %'uB of %'uB of %s",(ub4)nr,(ub4)slen,path); return 1; }

  lsp->orgsrc = sp;
  if (*sp == 0xef && slen > 2 && sp[1] == 0xbb && sp[2] == 0xbf) { // skip utf8 bom
    sp += 3; slen -= 3;
    if (slen == 0) { info("%s is an empty utf-8 bom",path); return 0; }
  }

  memset(sp+slen,0,xlen-slen);
  sp[slen++] = '\n';

  ipath = minalloc(n+1,1,Mnofil,"lex inc path");
  memcpy(ipath,path,n);
  ipath[n] = 0;

  p = ipath + n;
  while (p > ipath && p[-1] != '/') p--;
  fb->name = p;
  fb->path = ipath;
  fb->dirsep = dirsep;
  fb->len = slen;
  fb->incdir = incdir;

  if (verbose) timeit2(&T1,slen,"read ` in");
  msgfls();

  srcnam = path + dirsep;

  lsp->srclen = slen;

  if (globs.rununtil == 1) { infofln(FLN,"until file"); return 0; }

  rv = lex(fb,sp,slen,lsp,T1);

  msgfls();

  if (rv || lsp->tkcnt == 0) return rv;

  timeit2(&T0,slen,"tokenised ` in");

  return 0;
}

int lexstr(const unsigned char * restrict str,ub2 slen,struct lexsyn *lsp,ub8 T0)
{
  ub8 T1 = T0;
  struct fnaminf *fb;
  int rv;

  fb = getsrcmfile();
  fb->path = srcnam = "(cmdline)";

  char *src = minalloc(slen + 8,1,0,"lex -c src");
  memcpy(src,str,slen);
  src[slen++] = '\n';

  fb->len = slen;
  rv = lex(fb,src,slen,lsp,T1);

  if (rv) return rv;

  timeit2(&T0,slen,"tokenised ` in");
  return 0;
}

cchar *lex_info(void) {
  return lexinfo;
}

void inilex(void)
{
  ub4 hc,i;

  verbose = globs.msglvl >= Vrb;

  tracestate = dialvls[Dia_trc_state1];
  tracetok = dialvls[Dia_trc_tk1];

#ifdef Addtrace
  if (tracestate) infofln(FLN,"state trace on");
  if (tracetok) infofln(FLN,"token trace on");
#endif

  sassert(sizeof(ctab) == 256,"short enums required");

  infofln(hi32,"%s\n",lexinfo);

  // check genlex used same hash as us
#if Kwcnt > 0
  i = sizeof(tkwnampool);
  hc = hashalstr(tkwnampool,i,Hshseed);
  if (hc != kwnamhsh) {
    ice(0,"lexer inconsistent kwd hash %s: %x versus genlex: %x len %u seed %x '%.*s'",globs.prgnam,hc,kwnamhsh,i,Hshseed,i,tkwnampool);
  }
#endif

  lastcnt
}
