/* lexdef.h - lexer definitions

   generated by genlex 0.1.0-alpha  5 May 2022  0:09

   from minipython.lex 0.1.0  4 May 2022 23:07 minipython
   options: code yes  tokens yes  trace no
 */
static const char specnam[] = "minipython.lex";

static const char lexinfo[] = "minipython.lex 0.1.0   4 May 2022 23:07 minipython  code yes  tokens yes  trace no";

#define Cclen 4

#define Kwhshmask 3
#define Kwhshbit  2

#define x t99_count

static const ub1 kwhsh[4] = {
  x  ,1  ,0  ,3  };
#undef x

static const ub1 hikwlen = 5;
static const ub1 mikwlen = 5;
#define setkwd(T,t,k) T = k

static const ub1 kwgrps[4] = { 1,0,0,0 };

#define Hshseed   0x45cbf0ad
#define Hshdseed  0x0
#define Hshdshift 0x0
static inline enum Token lookupkw2(ub1 c,ub1 d)
{
       if (c == 'i' && d == 'f') return Tif;
  else return T99_count;
}

static const unsigned char kwhshlut[256] = {
    0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 32,  0,  0,  0,  2,
    0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0, 64,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 32,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 64,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
}; // 4,8

#define lookupblt2(c,d) B99_count

#define lookupdun2(c,d) D99_count

#define Lxercnt 1
enum Lxerror {
  Lxe_str_nl   =  0, Lxe_count    =  1, };

#define AF 0  // ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
#define NM 1  // 0123456789
#define WS 2  //  
#define HT 3  // \t
#define CR 4  // 0x0d
#define NL 5  // \n
#define HS 6  // #
#define QQ 7  // "'
#define CO 8  // {
#define CC 9  // }
#define RO 10 // (
#define RC 11 // )
#define CL 12 // :
#define SM 13 // ;
#define DT 14 // .
#define PM 15 // +-
#define ST 16 // *
#define O1 17 // /
#define O2 18 // %
#define O3 19 // @
#define O4 20 // <
#define O5 21 // >
#define O6 22 // &
#define O7 23 // |
#define O8 24 // ^
#define O9 25 // !
#define EOF 26 // 0x00
#define AN 1  // +0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
#define HX 2  // +ABCDEFabcdef
#define x  27

static unsigned char ctab[256] = {
  26,x ,x ,x ,x ,x ,x ,x ,x ,HT,NL,x ,x ,CR,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  WS,O9,QQ,HS,x ,O2,O6,QQ,RO,RC,ST,PM,x ,PM,DT,O1,
  NM,NM,NM,NM,NM,NM,NM,NM,NM,NM,CL,SM,O4,x ,O5,x ,
  O3,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,
  AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,x ,x ,x ,O8,AF,
  x ,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,
  AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,AF,CO,O7,CC,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,
  x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x ,x 
};
#undef x
#undef AF
#undef NM
#undef WS
#undef HT
#undef CR
#undef NL
#undef HS
#undef QQ
#undef CO
#undef CC
#undef RO
#undef RC
#undef CL
#undef SM
#undef DT
#undef PM
#undef ST
#undef O1
#undef O2
#undef O3
#undef O4
#undef O5
#undef O6
#undef O7
#undef O8
#undef O9
#undef EOF
#undef AN
#undef HX

static unsigned char utab[256] = {
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,3  ,3  ,3  ,3  ,3  ,3  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  ,0  ,0  ,1  ,
  0  ,3  ,3  ,3  ,3  ,3  ,3  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  
};

