/* lexdef.h - lexer definitions */

/* generated by genlex 0.1.0-alpha 17 Apr 2022  9:43

   from python.lex 0.1.0 17 Apr 2022  9:41 python-3.10
   options: code yes  tokens yes  trace no
 */

static const char specnam[] = "python.lex";

static const char lexinfo[] = "python.lex 0.1.0  17 Apr 2022  9:41 python-3.10  code yes  tokens yes  trace no";

#define Cclen 4

#define Kwhshmask 31
#define Kwhshbit  5

#define x t99_count

static const ub1 kwhsh[32] = {
  x  ,5  ,11 ,x  ,x  ,10 ,7  ,20 ,0  ,x  ,3  ,x  ,21 ,x  ,23 ,x  ,
  x  ,22 ,8  ,9  ,x  ,x  ,4  ,15 ,6  ,12 ,13 ,x  ,18 ,2  ,x  ,x  
  };
#undef x

static const ub1 hikwlen = 8;
static const ub1 mikwlen = 5;
static const ub1 kwhshmap[24] = { 0,1,2,3,4,5,6,7,8,9,10,11,12,12,13,14,15,16,17,18,19,20,21,22 };

#define setkwd(T,t,k) T = kwhshmap[k]; t = k

#define Hshseed   0x994a2900
#define Hshdseed  0x0
#define Hshdshift 0x0
static inline enum Token lookupkw2(ub1 c,ub1 d)
{
       if (c == 'a' && d == 's') return Tas;
  else if (c == 'i' && d == 'f') return Tif;
  else if (c == 'i' && d == 'n') return Tin;
  else if (c == 'i' && d == 's') return Tis;
  else if (c == 'o' && d == 'r') return Tor;
  else return T99_count;
}

static const unsigned char kwhshlut[256] = {
    1,  8,  1,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,105,  0,  0,
    0,  0,  0,  0,  0,  0,  2,  4,  0,  0, 16,  0,  0, 64,  0,  0,
   32,  0,  0,  0,  0,128,  0,  0,  2,  0, 64,  0,  0,  0,  0,  0,
   12,  0,  0,  0,  0,  0,  0,  9,  0,  0,  4,132,128,  2,  0,  0,
    4,  0, 66,  2,  0,  0,  2,  0, 64,  0,  0,  0, 32, 80,  0, 32,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 48,  0,  0,  0,  0,
    0,  0,  4,  0,  0,  0, 16,  0,  0, 32,  0,  0,  0, 64,  0,  1,
  132,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0,  0,  0,  0,  0, 64,
    0,  0,  0,  0,  0,  0, 32,  0,  0,128,  0,  0,  0,  0,  0,  0,
   16,  0,  0,  2,  0,  0,  0, 32,  0,  0,  0,  1,  0,  0,  0,  0,
    0,128,  0,  1,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,
    0,  0,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,
    0,  0,  0,  0, 10,  0,  0,  0,  0, 12,  0,  0,  0,  8,  0,  4,
    0,  0, 64,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
    0,  0,  0,  0,  0,  0, 16,  3,  0,  0,  0,128, 32,  8,  0,  0,
    0,  0,  0,  0,  0,  0, 16,  0,  8,  0,  0,  0,  0,  2,  0,  0
}; // 34,33

#define lookupblt2(c,d) B99_count

#define lookupdun2(c,d) D99_count

#define Lxercnt 1
enum Lxerror {
  Lxe_str_nl   =  0, Lxe_count    =  1, };

#define AF 0  // ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
#define NM 1  // 0123456789
#define WS 2  //  
#define HT 3  // \t
#define CR 4  // 0x0d
#define NL 5  // \n
#define HS 6  // #
#define QQ 7  // "'
#define CO 8  // {
#define CC 9  // }
#define SO 10 // [
#define SC 11 // ]
#define RO 12 // (
#define RC 13 // )
#define CL 14 // :
#define SM 15 // ;
#define CA 16 // ,
#define DT 17 // .
#define PM 18 // +-
#define ST 19 // *
#define EQ 20 // =
#define OP 21 // !%&/<>@^|
#define EOF 22 // 0x00
#define AN 1  // +0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz
#define PX 2  // +BFRUbfru
#define HX 4  // +ABCDEFabcdef
#define MN 8  // +\t\n !#%&)+,-/:;<>@]^|
#define XP 16 // +ACDEGHIJKLMNOPQSTVWXYZ_acdeghijklmnopqstvwxyz
#define X  23

static unsigned char ctab[256] = {
  EOF,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,HT ,NL ,X  ,X  ,CR ,X  ,X  ,
  X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,
  WS ,OP ,QQ ,HS ,X  ,OP ,OP ,QQ ,RO ,RC ,ST ,PM ,CA ,PM ,DT ,OP ,
  NM ,NM ,NM ,NM ,NM ,NM ,NM ,NM ,NM ,NM ,CL ,SM ,OP ,EQ ,OP ,X  ,
  OP ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,SO ,X  ,SC ,OP ,AF ,
  X  ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,CO ,OP ,CC ,X  ,X  ,
  X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,
  X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,
  X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,
  X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,X  ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,
  AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,AF ,X  ,X  
};
#undef X
#undef AF
#undef NM
#undef WS
#undef HT
#undef CR
#undef NL
#undef HS
#undef QQ
#undef CO
#undef CC
#undef SO
#undef SC
#undef RO
#undef RC
#undef CL
#undef SM
#undef CA
#undef DT
#undef PM
#undef ST
#undef EQ
#undef OP
#undef EOF
#undef AN
#undef PX
#undef HX
#undef MN
#undef XP

static unsigned char utab[256] = {
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,8  ,8  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  8  ,8  ,0  ,8  ,0  ,8  ,8  ,0  ,0  ,8  ,0  ,8  ,8  ,8  ,0  ,8  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,8  ,8  ,8  ,0  ,8  ,0  ,
  8  ,21 ,7  ,21 ,21 ,21 ,7  ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,
  17 ,17 ,3  ,17 ,17 ,3  ,17 ,17 ,17 ,17 ,17 ,0  ,0  ,8  ,8  ,17 ,
  0  ,21 ,7  ,21 ,21 ,21 ,7  ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,17 ,
  17 ,17 ,3  ,17 ,17 ,3  ,17 ,17 ,17 ,17 ,17 ,0  ,8  ,0  ,0  ,0  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,1  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,
  0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  ,0  
};

