/* syn.c - syntax analysis aka parsing

   This file is part of Morelia, a subset of Python with emphasis on efficiency.

   Copyright © 2022 Joris van der Geer.

   Morelia is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   mpy is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program, typically in the file License.txt
   If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

#include "base.h"
#include "chr.h"

#include "mem.h"

#include "fmt.h"

static ub4 msgfile = Shsrc_syn;
#include "msg.h"

#include "tok.h"
#include "lexsyn.h"

#include "syn.h"

// generated by gensyn
#include "syntab.i"

#ifdef __clang__
 #pragma clang diagnostic ignored "-Wenum-conversion"
 #pragma clang diagnostic ignored "-Wswitch-enum"
#elif defined __GNUC__
 #pragma GCC diagnostic ignored "-Wunused-variable"
#endif

struct node {
  enum Production se;

  ub1 acnt;
  ub1 lvl;
  ub1 x;

  ub4 ai;
  ub4 sib;
};

#define Depth 128

#define Trace

static bool dotrace = 1;

static cchar *tknam(enum Token tk,ub4 bits)
{
  ub2 len;
  ub1 hc;
  char *p,*q;
  static char basbuf[8 * 32];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 32;
  bufno = (bufno + 1) & 7;

  if (tk >= T99_count) return "Tinv";
#if Kwcnt > 0
  else if (tk < T99_kwd) {
    memcpy(buf,kwnampool + kwnamposs[tk],len=kwnamlens[tk]);
    buf[len] = 0;
  }
#endif
  else {
    tk -= T99_kwd;
    hc = tokhrctl[tk];
    len = hc & 0xf;
    if (len == 0) return toknampool + toknampos[tk];
    p = hrtoknams + tk * 4;
    q = buf;
    hc >>= 4;
    while (len--) {
      if (hc & 1) *q = bits & 0xf;
      else *q = *p;
      p++; q++;
      hc >>= 1; bits >>= 8;
    }
    *q = 0;
  }
  return buf;
}

static cchar *mrgnam(ub2 m,const char *sep)
{
  ub4 mrg = 1U << m;
  enum Token t;
  ub4 pos = 0,len = 255;
  static char basbuf[256 * 4];
  char *buf;
  static ub2 bufno;

  buf = basbuf + + bufno * 256;
  bufno = (bufno + 1) & 3;

  for (t = 0; t < T99_count; t++) {
    if (tkmrgtab[t] & mrg) {
      pos += mysnprintf(buf,pos,len,"%.*s'%s'",pos,sep,tknam(t,hi32));
    }
  }
  return buf;
}

static cchar *ntnam(enum Nterm n)
{
  if (n < Ncount) return ntnampool + ntnampos[n];
  else return "*Ninv*";
}

static cchar *symnam(enum Symbol s)
{
  if (s < Stoken) return tknam((enum Token)s,0);
  else if (s < Smrgset) return ntnam(s - Stoken);
  else if (s < Scount) return mrgnam(s - Smrgset,"|");
  else return "Seof";
}

static cchar *prodnam(enum Production p)
{
  if (p == Pcount) return "None";
  else if (p == Pendrep) return "Endrep";
  else if (p >= Plaid) return "LA";
  else return prodnampool + prodnampos[p];
}

static void printfirst(enum Nterm n)
{
  enum Token tk;
  const enum Production *pp;

  pp = prdsel + n * Stbl_tklen;
  info("%s first:",ntnam(n));
  for (tk = 0; tk < T99_count; tk++) {
    if (pp[tk] < Pendrep) info("  %s",tknam(tk,0));
  }
}

enum Sermsg {
  Ser_nil,
  Ser_nofirst,
  Ser_noexp,
  Ser_exp_tk_nomatch,
  Ser_exp_tk_nomatch1n,
  Ser_eof,
  Ser_noeof,
  Ser_eof_nostart,
  Ser_nola
};

static void ser(ub4 shfln,
  enum Token tk,
  ub4 bits,
  ub4 fpos,
  ub4 ti,
  enum Nterm r,
  ub2 si,enum Sermsg sm,enum Symbol xps,ub1 ctl,
  enum Production se)
{
  const struct sentry *ep;
  const struct seinfo *eip;
  enum Symbol s;
  const enum Symbol *sp;
  const enum Production *xep;
  enum Nterm xpr;
  enum Token mtk;
  enum Ctl z,repc;
  const enum Ctl *cp;
  enum Satrs atr=Sa_none;
  ub1 ns;
  ub2 si0;
  cchar *msg="";
  cchar *xpmsg="";
  char buf[1024];
  ub2 len = 1024;
  ub4 pos,pos2=0;
  enum Production xse;
  ub2 mbit,cnt;
  ub1 repsym[Scount+1];
  bool haverep = 0;

  switch(sm) {
    case Ser_nil: msg = "nil"; break;
    case Ser_nofirst: msg = "nofirst"; break;
    case Ser_exp_tk_nomatch: msg = "nomatch"; break;
    case Ser_exp_tk_nomatch1n: msg = "nomatch1n"; break;
    case Ser_eof: msg = "eof"; break;
    case Ser_noeof: msg = "noeof"; xpmsg = "<eof>"; break;
    case Ser_eof_nostart: msg = "eof nostart"; break;
    case Ser_noexp: msg = "noexp"; break;
    case Ser_nola: msg = "nola"; break;
  }

  pos = mysnprintf(buf,0,len,"ti %u %s: expected: %s",ti,msg,xpmsg);

  printfirst(r);

  if (sm != Ser_noeof) {
    if (xps < Stoken) pos += mysnprintf(buf,pos,len,"tk.'%s'",tknam(xps,0));
    else if (xps < Smrgset) {
      xpr = xps - Stoken;
      xep = prdsel + (ub2)xpr * Stbl_tklen;
      cnt = 0;
      for (mtk = 0; mtk < T99_count; mtk++) {
        xse = xep[mtk];
        if (xse != Pcount && xse != Pendrep) {
          pos += mysnprintf(buf,pos,len,"%.*s'%s'",cnt++,",",tknam(mtk,hi32));
        }
      }
    } else {
      mbit = 1U << (xps - Smrgset);
      cnt = 0;
      for (mtk = 0; mtk < T99_count; mtk++) {
        if (tkmrgtab[mtk] & mbit) {
          if (cnt++) buf[pos++] = ',';
          pos += mysnprintf(buf,pos,len," '%s'",tknam(mtk,hi32));
        }
      }
    }
    if (ctl) pos += mysnprintf(buf,pos,len," z=%02x",ctl);
  }

  switch (se) {
  case Pcount:  break;
  case Pendrep:   pos += mysnprintf(buf,pos,len,"end of rep at %s", tknam(tk,bits)); break;
  default: break;
  }

  if (se < Ptablen) {
    ep = syntab + se;

    sp = ep->syms;
    cp = ep->ctls;
    atr = syntabeas[se];
    ns = atr & Sa_len;
    s = sp[si];

    eip = stinfo + se;
    svrb(fpos,"si %u ln %u",si,eip->lno);

    pos += mysnprintf(buf,pos,len,"\n%s.%s representing '%s' at %s.%u\n",ntnam(r),prodnam(se),symnam(s),synfname,eip->lno);

    if (atr & Sa_s0) {
      pos += mysnprintf(buf,pos,len,"%s ",symnam(eip->s0));
    }

    memset(repsym,' ',Scount);
    si0 = 0;
    pos2 = pos;

    do {
      s = sp[si0];
      z = cp[si0];

      if (si0 == si) pos2 = pos;
      if (s < Smrgset) pos += mysnprintf(buf,pos,len,"%s%c ",symnam(s),repsym[s]);
      else pos += mysnprintf(buf,pos,len,"%s%c ",mrgnam(s - Smrgset,","),repsym[s]);
      if (repsym[s] == ' ') repsym[s] = '1';
      else { repsym[s]++; haverep = 1; }
      repc = z & Crepmask;
      if (repc == Crep01) buf[pos++] = '?';
      else if (repc == Crep0n) buf[pos++] = '*';

      if (si0 == si) {
        pos = pos2 + underline(buf + pos2,pos - pos2);
      }
      buf[pos++] = ' ';
      si0++;
    } while (--ns);
    if (haverep) pos += mysnprintf(buf,pos,len,"as %s",ntnam(r));
  }

  mysnprintf(buf,pos,len,", found '%s'\n",sm == Ser_eof ? "<eof>" : tknam(tk,bits));

  serrorfln(shfln,fpos,buf,nil);
}

static struct expmem nodemem;

#ifdef Tidctl
 static ub4 *lvlids[Depth];
 static ub4 lvlidpos[Depth];
#endif

#ifdef Trace
  #define sdia(lsp,ti,s,r,lvl,se,si,fmt,...) if (dotrace) diafln(FLN,lsp,ti,s,r,lvl,se,si,fmt,__VA_ARGS__)

static void __attribute__ ((format (printf,9,10))) diafln(
  ub4 shfln,
  struct lexsyn *lsp,
  ub4 ti,
  enum Symbol s,
  enum Nterm r,
  ub2 lvl,
  ub2 ve,
  ub2 si,
  cchar *fmt,...)
{
  static ub2 rowcnt;
  const enum Token * restrict tks = lsp->toks;
  const ub4        * restrict tkbits = lsp->tkbits;
  const ub4        * restrict tkpos = lsp->tkpos;
  enum Token tk = tks[ti];
  ub4 bits      = tkbits[ti];
  ub4 fpos      = tkpos[ti];

  char buf[256];
  ub2 lno=0;
  ub2 pos;
  enum Production se;
  enum Satrs atr=Sa_none;
  ub1 laid = 0xff;
  char c;
  cchar *pnam=nil;
  va_list ap;
  const struct sentry *ep=nil;
  const struct seinfo *eip=nil;
  const enum Symbol *sp;

  if ( (rowcnt++ & 31) == 0) infofln(hi32,"%-19s lvl rule           ve si sym            ti tk","");

  switch (ve) {
  case Pcount:  c = 'i'; break;
  case Pendrep: c = '*';  break;
  default: c = ' ';
    if (ve < Ptablen) {
      se = vprdmap[ve];
      ep = syntab + se; eip = stinfo + se;
      lno = eip->lno;
      atr = syntabeas[se];
      pnam = prodnam(se);
    } else if (ve >= Plaid) {
      laid = ve - Plaid;
    }
  }

  pos = mysnprintf(buf,0,256,"%2u %-14.12s %2u %u %-14.12s %2u %c%-8.6s",lvl,ntnam(r),ve,si,symnam(s),ti,c,tknam(tk,0));
//  pos += mysnprintf(buf,pos,256," %02x",bits);

  buf[pos++] = laid != 0xff ? '?' : ' ';
  buf[pos++] = (atr & Sa_rep) ? '*' : ' ';

  if (pnam) pos += mysnprintf(buf,pos,256," %-10.8s ",pnam);
  mysnprintf(buf,pos,256,"%.3u ",lno);

  if (ep) {
    sp = ep->syms;
    if (si) pos += mysnprintf(buf,pos,256,"%-10.8s ",symnam(sp[si-1]));
    pos += mysnprintf(buf,pos,256,"%-10.8s ",symnam(sp[si]));
  }

  // if (tk == Tid && bits < hi24) pos += mysnprintf(buf,pos,256,"'%.16s' ",lsp->idnampool + bits);

  while (pos < 60) buf[pos++] = ' ';
  buf[pos] = 0;

  va_start(ap,fmt);

  vmsgps(shfln,Info,fpos,fmt,ap,buf,nil);

  va_end(ap);
}
#else
  #define sdia(lsp,ti,s,r,lvl,se,si,fmt,...)
#endif

int syn(struct lexsyn *lsp)
{
  const enum Token * restrict tks = lsp->toks;
  const ub4 * restrict tkbits = lsp->tkbits;
  const ub4 * restrict tkpos = lsp->tkpos;

  ub4 tcnt = lsp->tkcnt;
//  cchar *srcnam = lsp->
  ub1 grp;

  if (tcnt == 0) ice(0,0,"%s empty token list","srcnam");

  ub4 ti = 0; // token index
  ub4 ni = 0; // node index

  ub2 lvl = 0,hilvl = 0;

  // main parser stack
  ub1 ves[Depth];
  ub1 sis[Depth];

  // synthesized args aka attributes
  // token index or node index
  ub4 args[Depth * Nodarg];
  ub2 argns[Depth * Nodarg];

  ub4 *ndargs;
  ub2 *ndargns;

  ub4 *argp;
  ub2 n,*argn;

  ub2 repcnt=0,repcnts[Depth];

  ub4 nids[Depth * Nodarg];

  ub4 fpos = 0;
  ub4 bits = 0;

  ub1 si = 0,len;
  ub2 nxndx;
  ub2 mrg;
  Mrgbits mrgbit;

  bool reppm,isrep;
  ub1 match=0;

  enum Token tk=0,tk1;
  const enum Symbol *sp=nil;
  enum Symbol s=0;
  enum Ctl z,repc,repcc,argc;
  enum Nterm nxr=0,r=startrule;
  enum Production se=0,nxse;
  ub1 ve,nxve;
  ub1 ai;
  const enum Ctl *cp=nil;

#ifdef Lacnt
  ub1 laid;
  ub1 lasn,lan;
  ub2 lasi;
  ub8 tkbit;
  lasec_t sec;
  const lasec_t *lasp;
#endif

  const struct sentry *ep=nil;

#ifdef Tidctl
  ub4 idcnt = lsp->idcnt;
  ub2 *iddefs = alloc(idcnt,ub2,0xff,"syn id defs");
#endif

  ub4 estndcnt = tcnt;

  for (grp = 1; grp < Tkgrps; grp++) estndcnt -= lsp->tkgrps[grp];

  nodemem.inc = 512;
  nodemem.ini = 64;
  nodemem.elsiz = sizeof(struct node);

  ub4 nodlim = estndcnt;

  ndargs = alloc(nodlim * 2,ub4,Mo_nofill,"node args",nextcnt);
  ndargns = alloc(nodlim * 2,ub2,Mo_nofill,"node args",nextcnt);

  // todo
  struct node *np,*nodes = blkexp(&nodemem,nodlim,struct node);

  ub4 nid;

  ub2 argcnt;
  ub4 napos=0;

  ub4 itercnt = 0,iterlim = tcnt * 8;

#ifdef Tidctl
  ub4 id,lidpos,*lidp;

  for (i = 0; i <= colvlhi; i++) {
    lvlidpos[i] = 0;
    lidpos = lsp->colvlidhi[i];
    if (lidpos) lvlids[i] = alloc(lidpos+1,ub4,0,"syn lvlids");
  }
#endif

  memset(sis,0xff,Depth); // mark max depth
  lvl = 0;

  info("parsing %u tokens",tcnt);
  si = 0;

  ve = startve;

  argp = args  + lvl * Nodarg;
  argn = argns + lvl * Nodarg;
  argn[0] = argn[1] = argn[2] = 0;

// -------------------
rulstart:
// -------------------

  if (ti >= tcnt) goto eof;

// select production
  sdia(lsp,ti,s,r,lvl,ve,si,"pos %u select",tkpos[ti]);

  ai = syntabeas[ve];

  if (ai & Sa_s0) {
    ti++;
  }
  se = vprdmap[ve];

  ep = syntab + se;
  sp = ep->syms;

  cp = ep->ctls;

  sdia(lsp,ti,*sp,r,lvl,ve,si,"se '%s'",stinfo[se].src);

// --- match production
  si = (ai >> 4) & 3;

  isrep = ai & Sa_rep;

  if (isrep) repcnts[lvl] = 0;

// -------------------
nxtsym:

// -------------------
  len = ai & 0xf;

  reppm = isrep;

  do { // each sym in clause

    // info("reppm %u isrep %u",reppm,isrep);

    if (si >= Slen) ice(0,fpos,"si %u",si);
    if (++itercnt > iterlim) ice(0,fpos,"iter lim %u",iterlim);

    tk = tks[ti];
    vrb("tk %u.%s ti %u si %u/%u",tk,tknam(tk,0),ti,si,len);

    s = sp[si];
    z = cp[si];

    repc = z & Crepmask;
    argc = z & Cargmask; // 1-based

    sdia(lsp,ti,s,r,lvl,ve,si,"z %x",z);

    if (s < Stoken) { // token = term

      match = (s == (enum Symbol)tk);

    } else if (s < Smrgset) { // nonterms -> push

      nxr = s - Stoken;
      nxndx = nxr * Stbl_tklen + tk;
      nxve = prdsel[nxndx];

#ifdef Lacnt
      if (nxve >= Plaid && nxve < Pendrep) { // lookahead
        laid = nxve - Plaid;
        lan = lasetn[laid];
        tk1 = tks[ti+1];
        tkbit = 1UL << tk1;

        lasi = lasecmap[laid * T99_count + tk];
        if (lasi != 255) {
          lasp = laseclst + lasi * Laset;
          for (lasn = 0; lasn < lan; lasn++) {
            sec = lasp[lasn];
            if (sec & tkbit) break;
          }
          sdia(lsp,ti,s,r,lvl,se,si,"laid %u %u/%u",laid,lasn,lan);
          if (lasn < lan) {
            sdia(lsp,ti,s,r,lvl,se,si,"la %u on tk %s",lasn,tknam(tk1,0));
            nxve = lasets[laid * Laset + lasn];
          } else ser(FLN,tk,bits,fpos,ti,nxr,si,Ser_nofirst,T99_count,z,se);
        } else ser(FLN,tk,bits,fpos,ti,nxr,si,Ser_nofirst,T99_count,z,se);
      } // la
#endif

      if (nxve < Ptablen) { // regular match -> push into new rule

        sdia(lsp,ti,s,r,lvl,se,si,"push into %s",ntnam(nxr));

        if (lvl + Skip >= Depth) ice(fpos,0,"exceeding %u nesting depth",lvl);

        sis[lvl] = si; // (repc == Crep0n ? si : si + 1);
        ves[lvl] = ve;
        lvl++;

        ve = nxve;

        argn = argns + lvl * Nodarg;
        argn[1] = argn[2] = 0;

        r = nxr;
        si = 0;

        argp = args  + lvl * Nodarg;

        if (isdeftok(tk)) {
          argn[0] = 1; argp[0] = ti;
        } else argn[0] = 0;

        goto rulstart;

      } else if (nxve < Pendrep) { // direct match -> nonterm
        sdia(lsp,ti,s,r,lvl,se,si,"direct match, node %u",ni);

        if (argc) {
          argc--;
          if (argn[argc] == 0) argp[argc] = ti;
          argn[argc]++;
        }

        if (repc != Crep0n) si++;
        ti++;

      } else if (nxve == Pendrep) { // rep of none
        sdia(lsp,ti,s,r,lvl,se,si,"rep of none %u",nxr);
        si++;

      } else { // nonmatch nterm
        sdia(lsp,ti,s,r,lvl,se,si,"no match repc %x",repc);
        if (repc == Crep01 || repc == Crep0n) si++; // common case
        else {
          repcc = repc >> Crepshift;
          if (repcc) {
            sdia(lsp,ti,s,r,lvl,se,si,"skip grp %u",repcc);
            si += repcc;
          } else ser(FLN,tk,bits,fpos,ti,nxr,si,Ser_nofirst,T99_count,z,se);
        }
      }

    } else if (s < Scount) { // merged tokens

      mrg = s - Smrgset;
      mrgbit = 1U << mrg;

      match = (tkmrgtab[tk] & mrgbit);

    } else {
      ser(FLN,tk,bits,fpos,ti,nxr,si,Ser_nofirst,T99_count,z,se);
    }

    if (s < Stoken || s >= Smrgset) { // term

      if (match) {
        sdia(lsp,ti,s,r,lvl,se,si,"match term %u len %u",z,len);

#ifdef Tidctl
        idc = z & Cidmask; // handle typedef-id

        if (tk == T0scop1) {
          if (scoplvl + 1 < Depth) scoplvl++; else { fpos = tkpos[ti]; ice(0,fpos,"scope exceeds %u at %s",scoplvl,tknam(s,0)); } break;
        } else if (tk == T0scop0) {
          if (scoplvl) scoplvl--; else { fpos = tkpos[ti]; ice(0,fpos,"scope below zero at %s",tknam(s,0)); } break;
        }

        switch (idc) {
        case Ciddef: id = tkbits[ti];
                     iddefs[id] = scoplvl;
                     break;

        case Cidref: id = tkbits[ti];
                     if (iddefs[id] <= scoplvl) {
                       tk = Ttypdefnam;
                     }
                     break;

        default: break;
        }
#endif

        if (argc) { // store first occurence as ti : others are at ti+n
          argc--;
          if (argn[argc] == 0) argp[argc] = ti;
          info("arg %u ti %u",argc,ti);
          argn[argc]++;
        }
        if (repc != Crep0n) si++;
//        info("ti %u",ti);
        ti++;

      } else { // nonmatch term

        info("tk %u.%s ti %u s %u.%s si %u/%u",tk,tknam(tk,0),ti,s,symnam(s),si,len);
        sdia(lsp,ti,s,r,lvl,se,si,"nonmatch term %s z %x",tknam(tk,0),z);

        if (repc == Crep01 || repc == Crep0n) si++; // common case
        else if (repc == Creplp) { vrb("ti %u",ti); reppm = 0; goto endsym; } // end rep
        else {
          repcc = repc >> Crepshift;
          if (repcc) {
            sdia(lsp,ti,s,r,lvl,se,si,"skip grp %u",repcc);
            si += repcc;
          } else ser(FLN,tk,bits,fpos,ti,nxr,si,Ser_nofirst,T99_count,z,se);

       } // generic case

      } // nonmatch

    } // term

  } while (si < len); // each sym in clause

// ------------
endsym:
// ------------

  if (argn[0]) {

    sdia(lsp,ti,s,r,lvl,se,si,"node %u",ni);

    if (ni + 1 >= nodemem.top) {
  //    maxndcnt += Ndchk;
    }
    if (ni >= nodlim) serror(fpos,"exceeded %u nodes",nodlim);

    np = nodes + ni;

    np->ai = napos;

    ndargs[napos] = argp[0];
    ndargns[napos] = argn[0];
    argcnt = 1;

    if (argn[1]) {
      ndargs[napos+1] = argp[1];
      ndargns[napos+1] = argn[1];
      argcnt = 2;

      if (argn[2]) {
        ndargs[napos+2] = argp[2];
        ndargns[napos+2] = argn[2];
        argcnt = 3;
      }
    }

    np->se = se;
    np->acnt = argcnt;
    napos += argcnt;

    np->lvl = lvl;
    ni++;
  } else argcnt = 0;

  nid = ni - 1;

  if (reppm) { // repeat rule
    repcnt = repcnts[lvl];
    if (repcnt == 0) nids[lvl] = nid;
    else if (argcnt) {
      nodes[ni-1].sib = nid = nids[lvl];
    }
    repcnts[lvl] = repcnt+1;

    tk = tks[ti];
    nxndx = r * Stbl_tklen + tk;
    nxve = prdsel[nxndx];
    if (nxve < Ptablen) {
      ve = nxve;
      ai = syntabeas[nxve];
      nxse = vprdmap[nxve];
      sdia(lsp,ti,s,r,lvl,nxse,si,"repeat on %u",se);
      si = (ai >> 4) & 3;
      argn[0] = argn[1] = argn[2] = 0;
      if (ai & Sa_s0) ti++;
      goto nxtsym;

    } else { // nonmatch at end of rep -> always ok end
      nxse = vprdmap[nxve];
      sdia(lsp,ti,s,r,lvl,nxse,si,"end rep on %u tk %s %u",se,tknam(tk,0),nxse);
    }
  } else {
    info("reppm %u isrep %u",reppm,isrep);
  }

  if (lvl == 0) {
//    icefln(FLN,hi32,tkpos[ti],"pop at lvl 0 after %u` tokens and %u` nodes",ti,ni);
    sinfo(tkpos[ti],"pop at lvl 0 after %u` tokens and %u` nodes",ti,ni);
    goto eof;
  }

  // pop. note: si not moved at push
  lvl--;
  si = sis[lvl];
  ve = ves[lvl];

  ai = syntabeas[ve];

  se = vprdmap[ve];

  ep = syntab + se;
  sp = ep->syms;

  cp = ep->ctls;

  isrep = ai & Sa_rep;
  len = ai & 0xf;

  argp = args + lvl * Nodarg;
  argn = argns + lvl * Nodarg;

  z = cp[si];
  repc = z & Crepmask;
  argc = z & Cargmask;

  if (argc) {
    argc--;
    info("ni %u argc %u",ni,argc);
    n = argn[argc];
    if (argn[argc] == 0 && reppm == 0) { // store first occurence
      nids[lvl] = nid;
      argp[argc] = nid | Nodarg;
    } else {
      nid = nids[lvl];
    }
    if (argcnt) nodes[ni-1].sib = nid;
    if (reppm) argns[argc] = repcnt;
    else argns[argc] = n+1;
  }

  if (repc == Crep11 || repc == Crep01) {
    si++;
  }

  r = prodrules[se];
  sdia(lsp,ti,s,r,lvl,se,si,"pop into %u lvl %u",r,lvl);
//  info("se %u si %u s %u",se,si,sp[si]);

  reppm = isrep;

  if (si >= len) goto endsym;
  else {
    goto nxtsym;
  }

  eof:

  info("ti %u bits %x",ti,tkbits[ti]);
  info("%u nodes",ni);

  hilvl = 0;
  while (hilvl < Depth && sis[hilvl] != 0xff) hilvl++;

  info("max lvl %u cur %u",hilvl,lvl);

//  if (r != startrule) { ser(FLN,tk,bits,fpos,ti,r,si,Ser_eof_nostart,T99_count,0,0); return 1; }

  if (globs.rununtil < 4) { info("until %u",globs.rununtil); return 1; }

  return 0;
}

cchar *syn_info(void) { return syninfo; }

int inisyn(void)
{
  ub4 i;
  enum Production prd;
  cchar *trc;

  sassert(sizeof(enum Token) == 1,"expected 8 bits tokens");
  sassert(sizeof(enum Production) == 1,"expected 8 bits productions");

  sassert(Tkpad > Syn_maxlen,"token padding accomodates max production len");

  ub4 slen = (ub4)sizeof(struct sentry);
  ub4 ilen = (ub4)sizeof(struct seinfo);
  ub4 len = poolsizes;

  info("pool %u`B",poolsizes);
  info("stab1 %3u * %2u = %3u`B",Ptablen,slen,(ub4)sizeof(syntab));
  info("stab2 %3u * %2u = %3u`B",Ptablen,ilen,(ub4)sizeof(stinfo));

#ifdef Lacnt
  info("la tab %u`B",Latabsizes);
  len += Latabsizes;
#endif
  len += sizeof(syntab);
  len += sizeof(stinfo);

  info("stpos %3u * %2u = %3u`B",Ncount,Stbl_tklen,(ub4)sizeof(prdsel));

  len += sizeof(prdsel);

  info("total          = %3u`B",len);

  for (i = 0; i < Ncount * T99_count; i++) {
    prd = prdsel[i];
    if (prd > Pcount) ice(0,hi32,"invalid symbol table entry %u at %u.%u",prd,i / T99_count,i % T99_count);
  }

#ifdef Lacnt
  info("productions with lookahead: %u",Lacnt);
#endif

#ifdef Trace
  trc = "en";
#else
  dotrace = 0;
  trc = "dis";
#endif
  info("tracing: %sabled, %s",trc,dotrace ? "on" : "off");

  lastcnt

  return 0;
}
