/* syn.c - syntax analysis aka parsing

   This file is part of Morelia, a subset of Python with emphasis on efficiency.

   Copyright © 2022 Joris van der Geer.

   Morelia is free software: you can redistribute it and/or modify
   it under the terms of the GNU Affero General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Morelia is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program, typically in the file License.txt
   If not, see http://www.gnu.org/licenses.
 */

#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

#include "base.h"
#include "chr.h"

#include "mem.h"

#include "fmt.h"

static ub4 msgfile = Shsrc_syn;
#include "msg.h"

#include "tok.h"
#include "lexsyn.h"

#include "syn.h"

#include "syndef.h" // generated by gensyn

#include "astyp.h"

#include "syntab.i" // generated by gensyn

#include "synast.h"

#ifdef __clang__
 #pragma clang diagnostic ignored "-Wenum-conversion"
 #pragma clang diagnostic ignored "-Wswitch-enum"
#elif defined __GNUC__
 #pragma GCC diagnostic ignored "-Wunused-variable"
#endif

#define Depth 128

#define Emitdetail

#define Trace

static bool dotrace = 0;

static ub4 dirprds[256]; // todo

static cchar *tknam(enum Token tk,ub4 bits)
{
  ub2 len;
  ub1 hc;
  char *p,*q;
  static char basbuf[8 * 32];
  char *buf;
  static ub2 bufno;

  buf = basbuf + bufno * 32;
  bufno = (bufno + 1) & 7;

  if (tk >= T99_count) return "Tinv";
#if Kwcnt > 0
  else if (tk < T99_kwd) {
    memcpy(buf,kwnampool + kwnamposs[tk],len=kwnamlens[tk]);
    buf[len] = 0;
    buf[len+1] = ' ';
  }
#endif
  else {
    tk -= T99_kwd;
    hc = tokhrctl[tk];
    len = hc & 0xf;
    if (len == 0) return toknampool + toknampos[tk];
    p = hrtoknams + tk * 4;
    q = buf;
    if (bits == hi32) hc = 0;
    else hc >>= 4;
    while (len--) {
      if (hc & 1) *q = bits & 0xf;
      else *q = *p;
      p++; q++;
      hc >>= 1; bits >>= 8;
    }
    *q = 0;
    q[1] = ' ';
  }
  return buf;
}

static cchar *mrgnam(ub2 m,char sep)
{
  ub4 mrg = 1U << m;
  enum Token t;
  ub4 pos = 0,len = 255;
  static char basbuf[256 * 4];
  char *buf;
  static ub2 bufno;

  buf = basbuf + + bufno * 256;
  bufno = (bufno + 1) & 3;

  for (t = 0; t < T99_count; t++) {
    if (tkmrgtab[t] & mrg) {
      if (pos) buf[pos++] = sep;
      pos += mysnprintf(buf,pos,len,"%s",tknam(t,hi32));
    }
  }
  return buf;
}

static cchar *ntnam(enum Nterm n)
{
  if (n < Ncount) return ntnampool + ntnampos[n];
  else return "*Ninv*";
}

static cchar *symnam(enum Symbol s)
{
  if (s < Stoken) return tknam((enum Token)s,0);
  else if (s < Smrgset) return ntnam(s - Stoken);
  else if (s < Scount) return mrgnam(s - Smrgset,'|');
  else return "Seof";
}

static cchar *prdnam(enum Production p,enum Token tk)
{
  if (p == Pcount) return "None ";
  else if (p == Pendrep) return "Endrep ";
  else if (p >= Plaid) return "LA ";
  else if (p >= Ptablen) return tknam(tk,0);
  else return prodnampool + prodnampos[p];
}

static void printfirst(enum Nterm n)
{
  enum Token tk;
  const enum Production *pp;

  pp = prdsel + n * Stbl_tklen;
  info("%s first:",ntnam(n));
  for (tk = 0; tk < T99_count; tk++) {
    if (pp[tk] < Pendrep) info("  %s",tknam(tk,0));
  }
}

enum Sermsg {
  Ser_nil,
  Ser_nofirst,
  Ser_noexp,
  Ser_exp_tk_nomatch,
  Ser_exp_tk_nomatch1n,
  Ser_eof,
  Ser_noeof,
  Ser_eof_nostart,
  Ser_nola
};

static void ser(ub4 shfln,
  struct lexsyn *lsp,
  enum Token tk,
  ub4 ti,
  enum Nterm r,
  ub2 si,enum Sermsg sm,enum Symbol xps,ub1 ctl,
  enum Production ve)
{
  const struct sentry *ep;
  const struct seinfo *eip;
  enum Symbol s;
  const enum Symbol *sp;
  const enum Production *xep;
  enum Nterm xpr;
  enum Token mtk;
  enum Ctl z,repc;
  const enum Ctl *cp;
  enum Satrs satr=Sa_none;
  ub4 fps;
  ub2 atr;
  ub1 ns;
  ub2 se;
  ub2 si0;
  cchar *msg="";
  cchar *xpmsg="";
  char buf[1024];
  ub2 len = 1024;
  ub4 pos,pos2=0;
  enum Production xse;
  ub2 mbit,cnt;
  ub1 repsym[Scount+1];
  bool haverep = 0;

  const ub2        * restrict atrs   = lsp->atrs;
  const ub8        * restrict tkbits = lsp->bits;
  const ub4        * restrict fpos   = lsp->fpos;

  switch(sm) {
    case Ser_nil: msg = "nil"; break;
    case Ser_nofirst: msg = "nofirst"; break;
    case Ser_exp_tk_nomatch: msg = "nomatch"; break;
    case Ser_exp_tk_nomatch1n: msg = "nomatch1n"; break;
    case Ser_eof: msg = "eof"; break;
    case Ser_noeof: msg = "noeof"; xpmsg = "<eof>"; break;
    case Ser_eof_nostart: msg = "eof nostart"; break;
    case Ser_noexp: msg = "noexp"; break;
    case Ser_nola: msg = "nola"; break;
  }

  atr = atrs[ti];
  fps = fpos[ti];
  pos = mysnprintf(buf,0,len,"ti %u %s: expected: %s",ti,msg,xpmsg);

  printfirst(r);

  if (sm != Ser_noeof) {
    if (xps < Stoken) pos += mysnprintf(buf,pos,len,"tk.'%s'",tknam(xps,0));
    else if (xps < Smrgset) {
      xpr = xps - Stoken;
      xep = prdsel + (ub2)xpr * Stbl_tklen;
      cnt = 0;
      for (mtk = 0; mtk < T99_count; mtk++) {
        xse = xep[mtk];
        if (xse != Pcount && xse != Pendrep) {
          pos += mysnprintf(buf,pos,len,"%.*s'%s'",cnt++,",",tknam(mtk,hi32));
        }
      }
    } else {
      mbit = 1U << (xps - Smrgset);
      cnt = 0;
      for (mtk = 0; mtk < T99_count; mtk++) {
        if (tkmrgtab[mtk] & mbit) {
          if (cnt++) buf[pos++] = ',';
          pos += mysnprintf(buf,pos,len," '%s'",tknam(mtk,hi32));
        }
      }
    }
    if (ctl) pos += mysnprintf(buf,pos,len," z=%02x",ctl);
  }

  switch (ve) {
  case Pcount:  break;
  case Pendrep:   pos += mysnprintf(buf,pos,len,"end of rep at %s", tknam(tk,atr)); break;
  default: break;
  }

  if (ve < Ptablen) {
    se = vprdmap[ve] & 0xff;
    ep = syntab + se;

    sp = ep->syms;
    cp = ep->ctls;
    satr = syntabeas[se];
    ns = satr & Sa_len;
    s = sp[si];

    eip = stinfo + se;
    sinfo(fps,"si %u/%u ln %u",si,ns,eip->lno);

    pos += mysnprintf(buf,pos,len,"\n%s.%s`z representing '%s' at %s.%u\n",ntnam(r),prdnam(se,0),symnam(s),synfname,eip->lno);

    if (satr & Sa_s0) {
      pos += mysnprintf(buf,pos,len,"%s ",symnam(eip->s0));
    }

    memset(repsym,' ',Scount);
    si0 = 0;
    pos2 = pos;

    do {
      s = sp[si0];
      z = cp[si0];

      if (si0 == si) pos2 = pos;
      if (s < Smrgset) pos += mysnprintf(buf,pos,len,"%s%c ",symnam(s),repsym[s]);
      else pos += mysnprintf(buf,pos,len,"%s%c ",mrgnam(s - Smrgset,','),repsym[s]);
      if (repsym[s] == ' ') repsym[s] = '1';
      else { repsym[s]++; haverep = 1; }
      repc = z & Crepmask;
      if (repc == Crep01) buf[pos++] = '?';
      else if (repc == Crep0n) buf[pos++] = '*';

      if (si0 == si) {
        pos = pos2 + underline(buf + pos2,pos - pos2);
      }
      buf[pos++] = ' ';
      si0++;
    } while (--ns);
    if (haverep) pos += mysnprintf(buf,pos,len,"as %s",ntnam(r));
  }

  mysnprintf(buf,pos,len,", found '%s'\n",sm == Ser_eof ? "<eof>" : tknam(tk,atr));

  serrorfln(shfln,fps,buf,nil);
}

#ifdef Trace
  #define sdia(lsp,ti,b,s,r,lvl,se,si,fmt,...) if (dotrace) sdiafln(FLN,lsp,ti,b,s,r,lvl,se,si,fmt,__VA_ARGS__)

static void __attribute__ ((format (printf,10,11))) sdiafln(
  ub4 shfln,
  struct lexsyn *lsp,
  ub4 ti,
  ub8 bits,
  enum Symbol s,
  enum Nterm r,
  ub2 lvl,
  enum Production ve,
  ub2 si,
  cchar *fmt,...)
{
  static ub2 rowcnt;
  const enum Token * restrict tks    = lsp->toks;
  const ub2        * restrict atrs   = lsp->atrs;
  const ub8        * restrict tkbits = lsp->bits;
  const ub4        * restrict fpos   = lsp->fpos;

  enum Token tk = tks[ti];
  ub2 lat,atr   = atrs[ti];

  ub4 fps = 0;
  ub4 len = 512;
  char buf[512];
  ub2 lno=0;
  ub2 pos,opos;
  ub2 n,x2;
  ub4 id;
  ub2 se=0;
  enum Satrs satr=Sa_none;
  ub1 laid = 0xff;
  char c;
  cchar *pnam=nil;
  va_list ap;
  const struct sentry *ep=nil;
  const struct seinfo *eip=nil;
  const enum Symbol *sp;

  fps = fpos[ti];

  if ( (rowcnt++ & 31) == 0) infofln(hi32,"%-19s lvl %-12s se si %-12s ti tk","","prod","sym");

  switch (ve) {
  case Pcount:  c = 'i'; break;
  case Pendrep: c = '*';  break;
  default: c = ' ';
    if (ve < Ptablen) {
      se = vprdmap[ve] & 0xff;
      ep = syntab + se; eip = stinfo + se;
      lno = eip->lno;
      satr = syntabeas[se];
      pnam = prdnam(se,0);
    } else if (ve >= Plaid) {
      laid = ve - Plaid;
    }
  }

  //                          lvl  prdnam    se  si symnam   ti     tk
  pos = mysnprintf(buf,0,len,"%2u %-14.12s`z %2u %u %-14.12s %2u %c%-8.6s %s",lvl,prdnam(ve,tk),se,si,symnam(s),ti,c,tknam(tk,0),ntnam(r));
//  pos += mysnprintf(buf,pos,256," %02x",bits);

#ifdef Emitdetail
    opos = pos;
    pos += mysnprintf(buf,pos,len,"atr %x ",atr);
    lat = atr & ~ La_msk; atr &= La_msk;
    switch ((ub1)tk) {
    case Tid:   if (lat == La_id4) pos += mysnprintf(buf,pos,len,"%lu",bits);
                break;
    case Tnlit: if (lat >= La_ilita) pos += mysnprintf(buf,pos,len,"%.7s",lsp->nlitpool + bits);
                else if (lat >= La_ilit4) pos += mysnprintf(buf,pos,len,"%lu",bits);
                else pos += mysnprintf(buf,pos,len,"%u",atr);
                break;
    case Tslit:
    case Tflit: id = hi32;
                if (lat == La_slits) id = atr;
                else if (lat == La_slit) id = bits;
                else if (lat == 0) buf[pos++] = atr;
                if (id != hi32) pos += mysnprintf(buf,pos,len,"%s",chprints(lsp->slitpool + id,6));
                break;
    default:    break;
    }
    while(pos < opos + 8) buf[pos++] = ' ';
#endif

  buf[pos++] = laid != 0xff ? '?' : ' ';
  buf[pos++] = (satr & Sa_rep) ? '*' : ' ';

  if (pnam) pos += mysnprintf(buf,pos,len," %-10.8s`z ",pnam);
  pos += mysnprintf(buf,pos,len,"%3u ",lno);

  if (ep) {
    sp = ep->syms;
    if (si) pos += mysnprintf(buf,pos,len,"%-10.8s ",symnam(sp[si-1]));
    pos += mysnprintf(buf,pos,len,"%-10.8s ",symnam(sp[si]));
  }

  while (pos < 60) buf[pos++] = ' ';
  buf[pos] = 0;

  va_start(ap,fmt);

  vmsgps(shfln,Info,fps,fmt,ap,buf,nil);

  va_end(ap);
}
#else
  #define sdia(lsp,ti,b,s,r,lvl,se,si,fmt,...)
#endif

int syn(struct lexsyn *lsp,struct synast *sa)
{
  const enum Token * restrict tks = lsp->toks;
  const ub2 * restrict atrs   = lsp->atrs;
  const ub8 * restrict tkbits = lsp->bits;
  const ub4 * restrict fpos   = lsp->fpos;

  ub4 *tkgrps = lsp->tkgrps;
  cchar *name = lsp->name;
  int rv = 0;

  ub4 tcnt = lsp->tkcnt;
  ub4 bcnt = lsp->tbcnt;
  ub1 grp;

  if (tcnt == 0) ice(0,0,"%s empty token list","srcnam");

  ub4 ti = 1; // token index
  ub4 bi = 0;
  ub4 ni2,ni1,ndcnt,ni = 0; // node index

  ub2 lvl = 0,prvlvl,hilvl = 0;

  // main parser stack
  ub1 ves[Depth];
  ub1 sis[Depth];
  ub1 ams[Depth];

  // synthesized args aka attributes
  // token index or node index
  ub4 args[Depth * Nodarg];
  ub4 arg,*argp;

  ub8 vals[Depth * Nodarg];
  ub8 val=0,*valp;

  ub2 n;

  ub2 curscope = 0,hiblklvl = 0,scid = 0;
  ub4 hiblkti=0;

  // repetitions
  ub2 rep,repcnt=0,repcnts[Depth];
  ub4 repfnids[Depth];
  ub4 replnids[Depth];

  ub4 ntfps=0,fps=0;
  ub8 bits = 0;
  ub4 bits4;
  ub4 idid;
  ub1 bits1,bit;

  ub1 si = 0,len;
  ub2 nxndx;
  ub2 mrg;
  Mrgbits mrgbit;

  bool isrep;
  ub1 match=0;

  enum Token tk=0,tk1;
  ub2 atr,lat;
  const enum Symbol *sp=nil;
  enum Symbol s=0;
  enum Ctl z,repc,repcc,argc;
  enum Nterm nxr=0,r=startrule;
  ub2 se=0,nxse,x2;
  ub4 ndti=0;
  enum Production ve,ve1,ve2=0,nxve;
  enum Bop bop;
  ub1 ai;
  ub4 x4;
  const enum Ctl *cp=nil;

#ifdef Lacnt
  ub1 laid;
  ub1 lasn,lan;
  ub2 lasi;
  ub8 tkbit;
  lasec_t sec;
  const lasec_t *lasp;
#endif

  const struct sentry *ep=nil;

  ub4 uidcnt = lsp->uidcnt;

  ub4 ndcnts[Acount+1];
  ub4 rep2cnts[Acount+1];

  memset(ndcnts,0,sizeof ndcnts);
  memset(rep2cnts,0,sizeof rep2cnts);

  ub2 uid1cnt = lsp->uid1cnt;
  ub2 uid2cnt = lsp->uid2cnt;
  ub4 idcnt = lsp->idcnt;

  sa->uidcnt = uidcnt + uid1cnt + uid2cnt;
  sa->idcnt = idcnt;

  // info("idcnt %u",idcnt);

  ub4 valcnt = idcnt + lsp->nlitcnt + lsp->slitcnt;
  sa->valcnt = valcnt;

  ub4 estxndcnt = tkgrps[1] + tkgrps[2]; // + ops + scope

  ub4 estndcnt  = tkgrps[0]; // storables
  ub4 estandcnt = estndcnt * hiruldep * 2;

  estndcnt  += estxndcnt;
  estandcnt += estxndcnt;

  if (estndcnt == 0) ice(0,hi32,"no nodes for %u tokens",tcnt);

  ub4 nodlim = estandcnt;

  ub4 *nhtab = alloc(estandcnt,ub4,Mnofil,"syn nhtab",nextcnt);
  ub4 *ndtis = alloc(estandcnt,ub4,Mnofil,"syn ndtis",nextcnt);

  ub4 *ndargs = alloc(nodlim * Nodarg,ub4,Mnofil,"syn ndargs",nextcnt);

  ub8 *ndvals = alloc(valcnt,ub8,Mnofil,"syn ndvals",nextcnt);
  sa->vals = vals;

  struct rnode *np,*np1,*np2,*nodes = alloc(nodlim,struct rnode,Mnofil,"syn nodes",nextcnt);
  ub4 *sibs = alloc(nodlim,ub4,Mnofil,"syn ndsibs",nextcnt); // siblings for rep

  ub4 nid=0,n4,nd,nn,aid=0,aidcnt;

  ub1 acnt;
  ub2 argcnt,cnt,am,ac;
  ub4 napos=0,nacnt,nvpos=0;

  ub4 itercnt = 0,iterlim = tcnt * 8;

  enum Astyp aty=0;

  memset(sis,0xff,Depth); // mark max depth
  lvl = 0;

  info("parsing %u`  tokens",tcnt);
  si = 0;

  ve = startve;

  repcnts[lvl] = 0;
  sis[lvl] = 0;
  ves[lvl] = ve;
  ams[lvl] = 0;
  lvl++;

  am = 0;
  argp = args + lvl * Nodarg;
  valp = vals + lvl * Nodarg;

// -------------------
rulstart:
// -------------------

//  if (ti >= tcnt) goto eof;

// select production
  ai = syntabeas[ve];

  sdia(lsp,ti,0,s,r,lvl,ve,si,"pos %u select ai %x",fps,ai);

  if (ai & Sa_s0) {
    ti++;
  }
  se = vprdmap[ve] & 0xff;

  ep = syntab + se;
  sp = ep->syms;

  cp = ep->ctls;

  sdia(lsp,ti,0,*sp,r,lvl,ve,si,"se '%s' len %u",stinfo[se].src,ai & 0xf);

// --- match production
  si = (ai >> 4) & 3;

  isrep = ai & Sa_rep;

  if (isrep) {
    repcnts[lvl] = 0;
    info("repcnt 0 at %u",lvl);
  }

// -------------------
nxtsym:

// -------------------
  len = ai & 0xf;

  do { // each sym in clause

    // info("reppm %u isrep %u",reppm,isrep);

    if (si >= Slen) ice(0,fps,"si %u",si);
    if (++itercnt > iterlim) ice(0,fps,"iter lim %u",iterlim);

    tk = tks[ti];
    fps = fpos[ti];

    sinfo(fps,"tk %u/%u %s",ti,tcnt,tknam(tk,0));
    // vrb("tk %u.%s ti %u si %u/%u",tk,tknam(tk,0),ti,si,len);

    s = sp[si];
    z = cp[si];

    repc = z & Crepmask;
    argc = z & Cargmask; // 1-based

    sdia(lsp,ti,0,s,r,lvl,ve,si,"z %x",z);

    if (s >= Stoken && s < Smrgset) { // nonterms -> push

      nxr = s - Stoken;
      nxndx = nxr * Stbl_tklen + tk;
      nxve = prdsel[nxndx];

#ifdef Lacnt
      if (nxve >= Plaid && nxve < Pendrep) { // lookahead
        laid = nxve - Plaid;
        lan = lasetn[laid];
        tk1 = tks[ti+1];
        tkbit = 1UL << tk1;

        lasi = lasecmap[laid * T99_count + tk];
        if (lasi != 255) {
          lasp = laseclst + lasi * Laset;
          for (lasn = 0; lasn < lan; lasn++) {
            sec = lasp[lasn];
            if (sec & tkbit) break;
          }
          sdia(lsp,ti,0,s,r,lvl,nxve,si,"laid %u %lx %u/%u",laid,tkbit,lasn,lan);
          if (lasn < lan) {
            sdia(lsp,ti,0,s,r,lvl,nxve,si,"la %u on tk %s",lasn,tknam(tk1,0));
            nxve = lasets[laid * Laset + lasn];
          } else ser(FLN,lsp,tk,ti,nxr,si,Ser_nofirst,T99_count,z,se);
        } else ser(FLN,lsp,tk,ti,nxr,si,Ser_nofirst,T99_count,z,se);
      } // la
#endif

      if (nxve < Ptablen) { // regular match -> push into new rule

#if 0
        if (nxve == P0block) {
          scid++;
          curscope++;
          if (curscope >= Depth) serror(fps,"scope exceeds %u at %s",curscope,tknam(s,0));
          else if (curscope > hiblklvl) { hiblklvl = curscope; hiblkti = ti; }
        }
#endif

        sdia(lsp,ti,0,s,r,lvl,nxve,si,"push %u into %s ve %u from %s`z",ve,ntnam(nxr),nxve,prdnam(ve,tk));

        if (lvl + Skip >= Depth) ice(fps,0,"exceeding %u nesting depth",lvl);

        sis[lvl] = si; // (repc == Crep0n ? si : si + 1);
        ves[lvl] = ve;
        ams[lvl] = am;
        lvl++;

        ve = nxve;

        r = nxr;
        si = 0;

        argp = args + lvl * Nodarg;
        valp = vals + lvl * Nodarg;
        am = 0;

        goto rulstart;

      } else if (nxve < P1dirtok) { // direct match as arg or kwd -> nonterm
        sdia(lsp,ti,0,s,r,lvl,nxve,si,"direct match, node %2u",ni);

        argc--;
        atr = atrs[ti];
        lat = atr & ~ La_msk; atr &= La_msk;
        switch (tk) {

          case Tid:
            if (lat == 0) idid = atr + uid1cnt + uid2cnt;
            else if (lat == La_id1) idid = atr;
            else if (lat == La_id2) idid = atr + uid1cnt;
            else if (lat == La_id4) {
              idid = tkbits[bi++];
#ifdef Bltcnt
            } else if (lat == La_idblt) {
              switch (atr) {
              case BTrue:  aty = Atru; break;
              case BFalse: aty = Afal; break;
              default:     aty = Aid;
              }
              if (aty != Aid) {
                ndti = 0;
                break;
              }
#endif
            } else if (lat == La_iddun) {
              idid = atr + 0;
            } else idid = 0;
            aty = Aid;
            ndti = ndcnts[aty]++;
            valp[argc] = idid | ((ub8)fpos << 32);
            break;

          case Tnlit:
            switch (lat) {
            case 0: ndti = atr; aty = Ailits; break;
            case La_ilit4:
              bits = tkbits[bi++];
              if (bits < Atymsk) { aty = Ailits; ndti = bits; }
              else aty = Ailit;
              break;
            case La_flit8: ice(0,0,"flt lits %x todo",atr);
            case La_ilita:
            case La_flita: ice(0,0,"ascii lits %u todo",atr);
            default: break;
            }
            if (aty != Ailits && aty != Ailitns) {
              ndti = ndcnts[aty]++;
              valp[argc] = bits;
            }
            break;

          case Tslit:
          case Tflit:
            switch (lat) {
            case 0:
            case La_slit: bits = tkbits[bi++];
            }

            aty = Aslit; ndti = ndcnts[aty]++;
            valp[argc] = bits | ((ub8)fpos << 32);
            break;

          default:
            aty = Akwd;
            if (tk < T99_mrg) ndti = tk;
            else ndti = atr;
            break;
        } // switch tk
        nhtab[aid] = ndti | (aty << Atybit);
        ndtis[aid] = ti;
        argp[argc] = aid++;
        am |= (1 << argc);
        info("arg %u %x t %u ve %u si %u",argc,argp[argc],aty,ve,si);

        if (repc != Crep0n) si++;
        ti++;
        continue;

      } else if (nxve < Plaid) { // idem, no arg
        sdia(lsp,ti,0,s,r,lvl,nxve,si,"direct match, node %2u arg",ni);

        if (repc != Crep0n) si++;
        ti++;

      } else if (nxve == Pendrep) { // rep of none
        sdia(lsp,ti,0,s,r,lvl,nxve,si,"rep of none %u",nxr);
        si++;

      } else { // nonmatch nterm
        sdia(lsp,ti,0,s,r,lvl,nxve,si,"no match repc %x",repc);
        if (repc == Crep01 || repc == Crep0n) si++; // common case
        else {
          repcc = repc >> Crepshift;
          if (repcc) {
            sdia(lsp,ti,0,s,r,lvl,nxve,si,"skip grp %u",repcc);
            si += repcc;
          } else if (ti >= tcnt) goto eof;
          else ser(FLN,lsp,tk,ti,nxr,si,Ser_nofirst,T99_count,z,se);
        }
      }

    } else {
      if (s < Stoken) { // token = term
        match = (s == (enum Symbol)tk);

      } else if (s < Scount) { // merged tokens
        mrg = s - Smrgset;
        mrgbit = 1U << mrg;
        match = (tkmrgtab[tk] & mrgbit);
      }

      if (match) {
        sdia(lsp,ti,0,s,r,lvl,ve,si,"match term %u len %u",z,len);

        if (argc) {
          argc--;
          atr = atrs[ti];

        lat = atr & ~ La_msk; atr &= La_msk;
        switch (tk) {

          case Tid:
            if (lat == 0) idid = atr + uid1cnt + uid2cnt;
            else if (lat == La_id1) idid = atr;
            else if (lat == La_id2) idid = atr + uid1cnt;
            else if (lat == La_id4) {
              idid = tkbits[bi++];
#ifdef Bltcnt
            } else if (lat == La_idblt) {
              switch (atr) {
              case BTrue:  aty = Atru; break;
              case BFalse: aty = Afal; break;
              default:     aty = Aid;
              }
              if (aty != Aid) {
                ndti = 0;
                break;
              }
#endif
            } else if (lat == La_iddun) {
              idid = atr + 0;
            } else idid = 0;
            aty = Aid;
            ndti = ndcnts[aty]++;
            valp[argc] = idid | ((ub8)fpos << 32);
            break;

          case Tnlit:
            switch (lat) {
            case 0: ndti = atr; aty = Ailits; break;
            case La_ilit4:
              bits = tkbits[bi++];
              if (bits < Atymsk) { aty = Ailits; ndti = bits; }
              else aty = Ailit;
              break;
            case La_flit8: ice(0,0,"flt lits %x todo",atr);
            case La_ilita:
            case La_flita: ice(0,0,"ascii lits %u todo",atr);
            default: break;
            }
            if (aty != Ailits && aty != Ailitns) {
              ndti = ndcnts[aty]++;
              valp[argc] = bits;
            }
            break;

          case Tslit:
          case Tflit:
            switch (lat) {
            case 0:
            case La_slit: bits = tkbits[bi++];
            }

            aty = Aslit; ndti = ndcnts[aty]++;
            valp[argc] = bits | ((ub8)fpos << 32);
            break;

          case Top: argp[argc] = atr; am |= (1 << argc);
                    break;
          default:  aty = Acount; break; // todo rep
          }

          if (aty <= Aleaf) {
            if (ndti >= Atymsk) serror(fps,"node count exceeds limit %u",Atymsk);
            nhtab[aid] = ndti | (aty << Atybit);
            ndtis[aid] = ti;
            info("arg %u t %u",argc,aty);
            argp[argc] = aid++;
            am |= (1 << argc);
          }
            // info("arg %u %x ve %u si %u",argc,argp[argc],ve,si);

        } // argc

        if (repc == Creplp) {
          ti++;
          goto endsym; // continue rep

        } else if (repc != Crep0n) si++;

        // info("ti %u",ti);
        ti++;

      } else { // nonmatch term

//        info("tk %u.%s ti %u s %u.%s si %u/%u",tk,tknam(tk,0),ti,s,symnam(s),si,len);
        sdiafln(FLN,lsp,ti,0,s,r,lvl,se,si,"nonmatch term %s z %x repc %x",tknam(tk,0),z,repc);

        if (repc == Crep01 || repc == Crep0n) si++; // common case
        else if (repc == Creplp) goto endsym; // end rep
        else {
          repcc = repc >> Crepshift; // crep2+
          if (repcc) {
            sdia(lsp,ti,0,s,r,lvl,se,si,"skip grp %u",repcc);
            si += repcc;
          } else ser(FLN,lsp,tk,ti,nxr,si,Ser_nofirst,T99_count,z,se);

       } // generic case

      } // nonmatch

    } // term

//    info("si %u/%u",si,len);
  } while (si < len); // each sym in clause

// ------------
endsym:
// ------------

  argc = 0;
  for (ac = 0; ac < Nodarg; ac++) {
    bit = 1 << ac;
    if ( (am & bit) == 0) continue;

    nn = argp[ac];
    nd = nhtab[nn];
    aty = nd >> Atybit;
    if (aty <= Aval) { // create leaf node
      info("val %lu for %s`z",valp[ac],atynam(aty));
      np = nodes + ni;
      np->ve = ve;
      np->lvl = lvl;
      np->amask = 0;
      np->ni = nn;
      nid = ni;
      ni++;
      if (ni >= nodlim) serror(fps,"exceeded %u nodes",nodlim);
      ndvals[nvpos++] = valp[ac];
    }
    argc++;
  }

  if (argc > 1) { // create node for this prd

    argc = 0;
    for (ac = 0; ac < Nodarg; ac++) {
      bit = 1 << ac;
      if ( (am & bit) == 0) continue;

    // arg
      nn = argp[ac];
      ndargs[napos++] = nn | ((ub4)argc << 30) | (ni << 16);
      argc++;
    }

    np = nodes + ni;
    np->ve = ve;
    np->lvl = lvl;

    sdia(lsp,ti,0,s,r,lvl,se,si,"node %2u",ni);

    np->amask = am;

    info("node %u argpos %u am %u argc %u ve %u",ni,napos,am,argc,ve);
    np->ve = ve;

#if 0
    np->blklvl = curscope;
    if (ve == P0block) {
      if (curscope) curscope--; else ice(hi32,fpos,"scope below zero at %s",tknam(tk,0));
    }
#endif

    aty = prd2nod[ve];
    info("ve %u %s`z typ %u %s`z",ve,prdnam(ve,0),aty,atynam(aty));
    ndti = ndcnts[aty]++;
    nhtab[aid] = ndti | (aty << Atybit);
    np->ni = aid++;
    info("node %u argc %u",ni,argc);

    nid = ni;
    ni++;
  } // argc > 1

  // info("reppm %u isrep %u ve %u",reppm,isrep,ve);

  if (isrep) { // repeat rule
    repcnt = repcnts[lvl];
    vrbo("repcnt %u at %u",repcnt,lvl);
    if (am) {
//      if (repcnt >= Repcnt) serror(fpos,"exceeding %u repeat count",repcnt);
      if (repcnt == 0) repfnids[lvl] = replnids[lvl] = nid;
      else {
        ni2 = replnids[lvl];
        sibs[ni2] = nid;
        replnids[lvl] = nid;
      }
      repcnts[lvl] = repcnt+1;
      vrbo("Repcnt %u at %u",repcnt+1,lvl);
    }
    if (match) {
      si = 0;
      goto nxtsym;

    } else { // nonmatch at end of rep -> always ok end
      sdiafln(FLN,lsp,ti,0,s,r,lvl,ve,si,"end rep on %u tk %s %u",se,tknam(tk,0),ve);

      if (repcnt > 1) { // create rep node
        np = nodes + ni;
        np->amask = repcnt;
        info("repnode %u argpos %u ve %u",ni,napos,ve);

        ni2 = repfnids[lvl];
        for (rep = 0; rep < repcnt; rep++) {
          np2 = nodes + ni2;
          ve2 = np2->ve;
          info("ve %u %s`z",ve,prdnam(ve,0));
          ndargs[napos++] = np2->ni;
          ni2 = sibs[ni2];
        }
        aty = Prd2nod[ve];
        if (repcnt == 2) rep2cnts[aty]++;
        ndti = ndcnts[aty]++;
        np->ni = aid;
        nhtab[aid++] = ndti | (aty << Atybit);
        np->ve = ve;
        np->lvl = lvl;
        info("rep node %u cnt %u ve %u.%u %s`z %s`z",ni,repcnt,ve,aty,prdnam(ve,0),atynam(aty));
        nid = ni++;
      } else info("rep node %u cnt %u ve %u",ni,repcnt,ve);
    }
  } else {
    info("isrep %u",isrep);
  }

  if (lvl == 0) {
    if (ti >= tcnt) {
//    icefln(FLN,hi32,fpos,"pop at lvl 0 after %u` tokens and %u` nodes",ti,ni);
      sinfo(fps,"pop at lvl 0 after %u` tokens and %u` nodes",ti,ni);
      goto eof;
    } else icefln(FLN,hi32,fps,"pop at lvl 0 after %u/%u tokens and %u` nodes",ti,tcnt,ni);
  }

  // pop. note: si not moved at push
  lvl--;

  si = sis[lvl];
  nxve = ves[lvl];
  am = ams[lvl];
  info("node %u nxve %u",ni,nxve);
  argp -= Nodarg;

  ai = syntabeas[nxve];

  x2 = vprdmap[nxve];

  sdia(lsp,ti,0,s,r,lvl,se,si,"pop into %s`z %u",prdnam(nxve,tk),x2 & 0xff);

  se = x2 & 0xff;
  r = x2 >> 8;

  ep = syntab + se;
  sp = ep->syms;

  cp = ep->ctls;

  len = ai & 0xf;

  z = cp[si];
  repc = z & Crepmask;
  argc = z & Cargmask;

  if (argc) {
    argc--;

#if 0
    if (reppm && repcnt > 2) {
      aty = prd2nod[ve2];
    } else {
      aty = prd2nod[ve];
    }
#endif

#if 1
    aty = prd2nod[ve];

    ndti = ndcnts[aty]++;
    sinfo(fps,"ni %u argc %u t %u %s`z",ni,argc,aty,atynam(aty));

    nhtab[aid] = ndti | (aty << Atybit);
    nodes[nid].ni = argp[argc] = aid++;
    am |= (1 << argc);
#endif
    sinfo(fps,"arg %u",argc);
  }

  ve = nxve;

  isrep = ai & Sa_rep;

  if (repc == Crep11 || repc == Crep01) {
    si++;
  }

//  info("se %u si %u s %u",se,si,sp[si]);

  if (si >= len) goto endsym;
  else {
    goto nxtsym;
  }

// ---
  eof:
// ---

  info("ti %u/%u bits %u/%u",ti,tcnt,bi,bcnt);
  showcnt("3node",ni);
  showcnt("3arg",napos);

  afree(sibs,"syn ndsibs",nextcnt);

  if (ti < tcnt) {
    info("ti %u/%u",ti,tcnt);
    ser(FLN,lsp,tk,ti,r,si,Ser_eof_nostart,T99_count,0,0);
    return 1;
  }

  if (ni == 0 || aid == 0) {
    info("nil nodes for %u tokens",tcnt);
    return 0;
  }

  cnt = ndcnts[Acount];
  if (cnt) ice(0,0,"%u invalid nodes",cnt);

  np = nodes + ni; // eof
  np->ni = aid;
  np->lvl = 0;
  np->amask = 0;
  nhtab[aid] = (ub4)Acount << Atybit;

  aidcnt = aid + 1;
  ndcnt = ni+1;
  nacnt = napos;

//  info("max scope depth %u at %u",hiblklvl,hiblkti);
//  showcnt("3scope blocks",scid);

  hilvl = 0;
  while (hilvl < Depth && sis[hilvl] != 0xff) hilvl++;

  info("max parser stack lvl %u",hilvl);
  if (lvl > 1) ice(hi32,fps,"syn eof at lvl %u",lvl);

//  if (r != startrule) { ser(FLN,tk,bits,fpos,ti,r,si,Ser_eof_nostart,T99_count,0,0); return 1; }

  if (globs.rununtil < 4) { info("until %u",globs.rununtil); return 1; }

  sa->nhs = nhtab;
  sa->nodes = nodes;
  sa->ndcnt = ndcnt;
  sa->aidcnt = aidcnt;
  sa->args = ndargs;
  sa->tis = ndtis;
  sa->argcnt = nacnt;
  sa->nscid = scid;
  sa->hiblklvl = hiblklvl;

  memcpy(sa->ndcnts,ndcnts,sizeof ndcnts);
  memcpy(sa->rep2cnts,rep2cnts,sizeof rep2cnts);

  bool emit = (globs.emit & Synpas);

  if (emit == 0) return rv;

  // emit parse tree
  char buf[512];
  ub4 blen = 512;
  ub4 pos;
  ub4 nh;
  enum Astyp nt;

//  msglog(name,"nds","syn");
  napos = 0;
  nvpos = 0;

  sinfofln(FLN,hi32,"nd  prod    lvl am");
  for (ni = 0; ni < ndcnt; ni++) {
    np = nodes + ni;
    ve = np->ve;
    prvlvl = lvl;
    lvl = np->lvl;
    am = np->amask;
    aid = np->ni;
    if (aid > aidcnt) ice(0,0,"aid %u out of range %u",aid,aidcnt);
    nh = nhtab[aid];
    ndti = nh & Atymsk;
    nt = nh >> Atybit;

    pos = mysnprintf(buf,0,blen,"%3u %3u.%u %u %x %*s %-8s`z %-8s`z",ni,aid,ndti,lvl,am,lvl," ",prdnam(ve,0),atynam(nt));
    vrbo("nd %u am %u pos %u ve %u %s`z",ni,am,napos,ve,atynam(nt));

    if (nt <= Aval) {
      if (nvpos >= valcnt) ice(0,0,"out of range var %u",nvpos);
      val = vals[nvpos++];
    }

    switch(nt) {
//    case Acount: ice(0,0,"node %u invalid type for ni %u",ni,aid);
    case Arexp:
    case Aprmlst:
    case Astmtlst:
      repcnt = am;
      napos += repcnt;
      if (napos > nacnt) ice(0,0,"arg %u/%u",napos,nacnt);
      pos += mysnprintf(buf,pos,blen," [%u]",repcnt);
    break;

    case Aid:
      x4 = val & hi32;
      fps = val >> 32;
      pos += mysnprintf(buf,pos,blen," id %u %u",x4,ndti);
    break;

    case Ailit:
      pos += mysnprintf(buf,pos,blen," ilit %lu %u",val,ndti); break;
    break;

    case Ailitn:
    case Aflit:

    case Aslit: // Aval
    break;

    case Ailits: pos += mysnprintf(buf,pos,blen," ilits %u",ndti); break;

    case Ailitns: break;

    case Atru:
    case Afal:
    case Akwd:

    case Aop:   break;

    default:
      bit = 1;
      argc = 0;
      while (bit < (1 << Nodarg)) {
        if (am & bit) {
          if (napos >= nacnt) ice(0,0,"nd %u arg %u/%u",ni,napos,nacnt);
          nn = ndargs[napos++];
          ac = nn >> 30; nn &= hi24;
          n4 = nn >> 16;
          nn &= hi16;
          if (ac != argc) ice(0,0,"nd %u arg %u/%u",ni,argc,ac);
          if (n4 != ni) ice(0,0,"nd %u arg %u nd %u",ni,argc,n4);
          nh = nhtab[nn];
          ndti = nh & Atymsk;
          nt = nh >> Atybit;
          pos += mysnprintf(buf,pos,blen," %u .%u %s`z.",argc,ndti,atynam(nt));
          vrbo("nd %u arg %u/%u %s`z",ni,argc,napos,atynam(nt));
        }
        bit <<= 1; argc++;
      }
    } // switch nt
    if (lvl > prvlvl) {
      ntfps = fps;
    }

    sinfofln(FLN,nt > Aleaf ? fps : ntfps,"%s",buf); pos = 0;
  }
  sinfofln(0,hi32,"EOF");

  msglog(nil,nil,"syn");
  if (napos != nacnt) ice(0,0,"arg %u vs %u",napos,nacnt);

  return rv;
}

cchar *syn_info(void) { return syninfo; }

int inisyn(void)
{
  ub4 i;
  enum Production prd;
  cchar *trc;

  sassert(sizeof(enum Token) == 1,"expected 8 bits tokens");
  sassert(sizeof(enum Production) == 1,"expected 8 bits productions");

  sassert(Tkpad > Syn_maxlen,"token padding accomodates max production len");

  ub4 slen = (ub4)sizeof(struct sentry);
  ub4 ilen = (ub4)sizeof(struct seinfo);
  ub4 len = poolsizes;

  if (globs.resusg) {
    info("pool %u`B",poolsizes);
    info("stab1 %3u * %2u = %3u`B",Ptablen,slen,(ub4)sizeof(syntab));
    info("stab2 %3u * %2u = %3u`B",Ptablen,ilen,(ub4)sizeof(stinfo));

#ifdef Lacnt
    info("la tab %u`B",Latabsizes);
    len += Latabsizes;
#endif
    len += sizeof(syntab);
    len += sizeof(stinfo);

    info("stpos %3u * %2u = %3u`B",Ncount,Stbl_tklen,(ub4)sizeof(prdsel));

    len += sizeof(prdsel);

    info("total          = %3u`B",len);
  }
  for (i = 0; i < Ncount * T99_count; i++) {
    prd = prdsel[i];
    if (prd > Pcount) ice(0,hi32,"invalid symbol table entry %u at %u.%u",prd,i / T99_count,i % T99_count);
  }

#ifdef Lacnt
  info("productions with lookahead: %u",Lacnt);
#endif

#ifdef Trace
  trc = "en";
#else
  dotrace = 0;
  trc = "dis";
#endif
  info("tracing: %sabled, %s",trc,dotrace ? "on" : "off");

  lastcnt

  return 0;
}
