// syndef.h - parser defines

/* generated by gensyn 0.1.0-alpha  5 May 2022  0:09

   from grammar minipython.syn version 0.1.0   5 May 2022  1:14 lang minipython
 */

static const char prodnampool[72] = 
  "stmts_0_0 stmts_0_1 stmt_0 stmt_1 if while block blk_stmt grpexp expr_0 ";

static const ub2 prodnampos[10] = { 0,10,20,27,34,37,43,49,58,65 };

enum Packed8 Production {
  Pstmts_0_0    =  0,Pstmts_0_1    =  1,Pstmt_0       =  2,Pstmt_1       =  3,
  Pif           =  4,Pwhile        =  5,Pblock        =  6,P0block       =  6,Pblk_stmt     =  7,
  Pgrpexp       =  8,Pexpr_0       =  9,Ptablen       = 10,Pnlit_atom    = 10,Pslit_atom    = 11,
  P1dirtok      = 12,
  Pbreak_stmt   = 12,Pid_atom      = 13,Plaid         = 14,Plaid_0       = 14,Pendrep       = 15,
  Pcount        = 16
};

