// tok.h - lexer token defines

/* generated by genlex 0.1.0-alpha 17 Apr 2022  9:43

   from python.lex 0.1.0 17 Apr 2022  9:41 python-3.10
 */

// signature: @ 15675cbba909692 @

enum Packed8 Token {
  Tand       =  0, Tas        =  1, Tassert    =  2, Tbreak     =  3, Tclass     =  4, Tcontinue  =  5, Tdef       =  6, Tdel       =  7,
  Telif      =  8, Telse      =  9, Tfor       = 10, Tfrom      = 11, Tglob_nl   = 12, Tif        = 13, Timport    = 14, Tin        = 15,
  Tis        = 16, Tnot       = 17, Tor        = 18, Tpass      = 19, Treturn    = 20, Twhile     = 21, T99_eof    = 21, Twith      = 22, 
  T99_kwd    = 23,

  Tnlit      = 23, Tslit      = 24, Tid        = 25, Tind       = 26, Tded       = 27, Tco        = 28, Tcc        = 29, Tro        = 30,
  Trc        = 31, Tso        = 32, Tsc        = 33, Tqas       = 34, Taas       = 35, Tdas       = 36, Tmulas     = 37, Tcolon     = 38,
  Tsepa      = 39, Tcomma     = 40, Tdot       = 41, Texp       = 42, Tast       = 43, Tpm        = 44, Tref       = 45, Top        = 46,
  
  T99_count  = 47
}; // gen.2646

#define Kwcnt 23
#define Tknamlen 8
#define Tkgrp 3

static const ub2 toknampos[25] = {
  0,5,10,13,17,21,24,27,30,33,36,39,43,47,51,57,63,68,74,78,82,86,89,93,96
};

static const char toknampool[96] = "nlit\0slit\0id\0ind\0ded\0co\0cc\0ro\0rc\0so\0sc\0qas\0aas\0das\0mulas\0colon\0sepa\0comma\0dot\0exp\0ast\0pm\0ref\0op\0";

enum Packed8 token { // gen.2478
  tand       =  0, tas        =  1, tassert    =  2, tbreak     =  3, tclass     =  4, tcontinue  =  5, tdef       =  6, tdel       =  7,
  telif      =  8, telse      =  9, tfor       = 10, tfrom      = 11, tglobal    = 12, tnonlocal  = 13, tif        = 14, timport    = 15,
  tin        = 16, tis        = 17, tnot       = 18, tor        = 19, tpass      = 20, treturn    = 21, twhile     = 22, twith      = 23,
  t99_count  = 24
};

static const ub1 kwnamlens[23] = { 3 ,2 ,6 ,5 ,5 ,8 ,3 ,3 ,4 ,4 ,3 ,4 ,7 ,2 ,6 ,2 ,2 ,3 ,2 ,4 ,6 ,5 ,4  };

static const ub2 kwnamposs[23] = { 0,3,5,11,16,21,29,32,35,39,43,46,50,57,59,65,67,69,72,74,78,84,89 };

static const char kwnampool[93] = "andasassertbreakclasscontinuedefdelelifelseforfromglob_nlifimportinisnotorpassreturnwhilewith";

static const ub1 tokhrctl[24] = { 0,0,0,0,0,1,1,1,1,1,1,2,0x12,1,2,1,1,1,1,2,1,0x11,2,0 };

static char hrtoknams[96] = "                    {   }   (   )   [   ]   :=  +=  =   *=  :   ;   ,   .   **  *   +   ->      "; // 24 * 4

enum Packed8 Bltin { B99_count = 1 };

enum Packed8 Dunder { D99_count = 1 };

static const char tkwnampool[132] = "and as  assert  break   class   continuedef del elifelsefor fromglobal  nonlocalif  import  in  is  not or  passreturn  while   with";
static const ub2  tkwnamposs[ 24] = { 0,4,8,16,24,32,40,44,48,52,56,60,64,72,80,84,92,96,100,104,108,112,120,128 };
static const ub1  tkwnamlens[ 24] = { 3,2,6,5,5,8,3,3,4,4,3,4,6,8,2,6,2,2,3,2,4,6,5,4 };

static const ub4 kwnamhsh = 0xe1ee40ec;

